### ISSUE TITLE
Start position for subdialogs

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/Instat#1014]
@africanmathsinitiative/instat  i am just wondering what position would be good for subdialogs start position. 
would it not be nice if it starts on the center of the parent dialog?

**Comment by dannyparsons** [comment]
Good question. I haven't thought about it. What are the different options?
It would be good for someone to research online to find out the
consequences of each choice.

**Comment by dannyparsons** [comment]
Still needs to be looked into and also links to #939 where we need to have a consistent start position for main dialogs too.

**Comment by maxwellfundi** [comment]
I am more happy with dialogs starting at the center screen. My opinions on
Sub Dialogs would be center screen but then they should be sent to front of
the main dialog.



Regards
Maxwell Fundi
|| Phone :+254728508241||

**Comment by dannyparsons** [comment]
Definitely sub dialogs need to be on top and users should not be unable to edit main dialogs when subdialogs are open. 
I'd like to understand when you might want to use the different positioning options. I'm sure it's been discussed online (StackOverflow) already so you could look into that maybe. I would guess it doesn't matter if you have a single screen with the program maximised. But once you have multiple screens and things of different sizes I'm sure the positioning makes a bigger difference.
Not that urgent but could be looked into when you have spare time.

**Comment by dannyparsons** [comment]
@lilyclements have you checked start position for sub dialogs as well?

**Comment by lilyclements** [comment]
Since I've only done the Organise menu so far, there haven't been many sub dialogs at all so far. I will continue with them in around an hour! Sorry!
In the "start position" do we want them to be central?

**Comment by dannyparsons** [comment]
Yes I think so, makes sense they appear on top or close to main dialog.

**Comment by lilyclements** [comment]
I've been making them "Central Parent", is that okay?
This way they are central, and if the user moved the main dialog on the screen and then clicked for the sdg to come up, it will come up in the middle of the dlg.

**Comment by dannyparsons** [comment]
That seems sensible

**Comment by maxwellfundi** [comment]
Yeah,  the sub dialogs should be at the center of the parent. I think
that's perfect

**Comment by FrancoisJRenaud** [comment]
Cecking this for all dialogues/subdialogues

**Comment by FrancoisJRenaud** [comment]
can be closed I think
