### ISSUE TITLE
Too many decimals in the output

### ISSUE THREAD

**Issue by Lunalo** [africanmathsinitiative/Instat#1019]
@africanmathsinitiative/instat 
Hello everyone.
I have been working on the row statistics dialog but in the process of returning output, I realized that the output contains several number of decimals which was varying
as shown below:
![rowstats](https://cloud.githubusercontent.com/assets/13945088/13536967/b60360b4-e253-11e5-9fde-fb87c22ca20f.PNG)

Does someone have an idea on how to solve this such that we have a standard number of decimals for all output?

**Comment by dannyparsons** [comment]
Has this been resolved?

**Comment by Lunalo** [comment]
Yes.
Polycarp has said that we specify standard number of decimals. of
which I thought of 4 decimal points

On 3/8/16, Danny Parsons <notifications@github.com> wrote:
> Has this been resolved?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/africanmathsinitiative/Instat/issues/1019#issuecomment-193686077


-- 
Regards,
John Ong'ala Lunalo|| Kenyatta University Alumnus||
Volunteer, African Maths Initiative||
Email Address :johnlunalo95@gmail.com
Tel: +254701519572, +254786438572

**Comment by dannyparsons** [comment]
Is this implemented? And I'm interested why you have chosen 4 decimal places as the default.

**Comment by Lunalo** [comment]
Good question.

It was my suggestion but after doing more research, i can say number
of decimal points will depend on the accuracy level needed

On 3/8/16, Danny Parsons <notifications@github.com> wrote:
> Is this implemented? And I'm interested why you have chosen 4 decimal places
> as the default.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/africanmathsinitiative/Instat/issues/1019#issuecomment-193714501


-- 
Regards,
John Ong'ala Lunalo|| Kenyatta University Alumnus||
Volunteer, African Maths Initiative||
Email Address :johnlunalo95@gmail.com
Tel: +254701519572, +254786438572
