### ISSUE TITLE
dlgRecode

### ISSUE THREAD

**Issue by nyagishira** [africanmathsinitiative/Instat#1060]
a)I need help to change default name of the new recode column
b)the ucrMlltipleInput can not be reset like the other controls, it needs to be looked into
c)

**Comment by dannyparsons** [comment]
Thanks for raising the issues.
a) Can we discuss this so I can understand the issue exactly.
b) Good point, I will look into that for this control

**Comment by nyagishira** [comment]
we can discuss a)

**Comment by nyagishira** [comment]
by using ucrInputTextBox visual studio is not displaying the output whereas when i run the code in R, R produces an output...we do know how to fix that yet. We need help
