### ISSUE TITLE
Excluded dialogs from the project

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/Instat#1112]
@africanmathsinitiative/instat  i was wondering if i could remove the excluded dialogs from the project if we are not using them so that we could have a clean master with only what we need. 
Kindly if you have an excluded file that you wish to use, include it to the project. 
I will be removing them tomorrow to make sure we have a clean master. 

many thanks

**Comment by dannyparsons** [comment]
How many excluded dialogs are there?

**Comment by maxwellfundi** [comment]
There are 12 excluded dialogs

Regards
Maxwell Fundi
|| Phone :+254728508241||

**Comment by dannyparsons** [comment]
@maxwellfundi Has this been completed now?

**Comment by maxwellfundi** [comment]
No, this hasnt been completed but i can fix them easily.

Regards
Maxwell Fundi
|| Phone :+254728508241||

**Comment by dannyparsons** [comment]
Not urgent, but if you're ever stuck for something to do, this could be done.
