### ISSUE TITLE
facet selector not linked to data frame selected on main dialog

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/Instat#1217]
The selector for facets on the plot subdialog does not update when the data frame is changed on the main dialog.

**Comment by maxwellfundi** [comment]
@dannyparsons, i think we can replace the selector on the subdialog with the one with the dataframeselector.,,

**Comment by dannyparsons** [comment]
This appears to still be an issue. We could link the selectors so that their data frames are in sync and disable the dataframe selector on the subdialog.

**Comment by dannyparsons** [comment]
Appears to be resolved.
