### ISSUE TITLE
Some datasets from packages give an error from R when attempting to load

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/Instat#1220]
This is only for the data sets where the name is not a valid R name e.g. "beaver1 (beavers)" in datasets package.

To load these datasets ignore everything after the space so "beaver1" loads correctly. Therefore we can just trim the name of everything after the first space to get the loading done correctly.

**Comment by dannyparsons** [comment]
@deaspo Could you fix this?

**Comment by maxwellfundi** [comment]
@africanmathsinitiative/instat i noticed also the datasets with the package Plotrix do not load. 
@dannyparsons  could you look into this?

**Comment by dannyparsons** [comment]
Thanks Maxwell for spotting this. In R I think this can be fixed by loading the data first through: data("datasetname"). I'm not sure exactly why this is only needed for this package. I will work on getting this extra line in the dialog.
