### ISSUE TITLE
dlgDeleteSheet not Reopening

### ISSUE THREAD

**Issue by Lunalo** [africanmathsinitiative/Instat#1531]
@africanmathsinitiative/instat 

Hello Team,

I have tried testing this log. At first I thought the dialog is working fine but when i tried reopen it could not reopen. The dialog is crushing in the R link. Someone ( @dannyparsons , @volloholic ) should look into this.

**Comment by dannyparsons** [comment]
Hi John, I'm not getting any such problem using the latest version. Can you try it again and if you still get the issue post more details back?

**Comment by dannyparsons** [comment]
This is fixed by #1534 by modifying the data frame user control
