### ISSUE TITLE
dplyr's arrange - no na.last parameter

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/Instat#1586]
dplyr's arrange does not have an na.last parameter which specifies where NAs should be placed in the sort. They are placed at the end. 

Is it important to be able to sort and place NAs at the top?

**Comment by rdstern** [comment]
It is important to have sort on multiple keys and also to be able to sort ascending or descending.  I don't have a particular problem where NAs go.  I would be concerned if they were at the top and you couldn't change that.  So if they are in a fixed place then at the end is fine by me.
If anyone wants the opposite, then they can do a replace by a large negative number and then sorting and then replace again!
