### ISSUE TITLE
Some dialogs are resizable

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/Instat#1696]
e.g. Regular Sequence. The dialog type should be changed and other dialogs should be checked. Related to #1695

**Comment by maxwellfundi** [comment]
@dannyparsons there are differences in properties of the dialogs- for the regualar sequence, both maximize and minimize box are false and the border style is sizable while for the calculator both maximize and minimize box are true but the formborderstyle is fixedtoolwindow. So when i changed the maximize and minimize box to false it worked fine. So , we have to be consistent with our form border style and make sure  maximize and minimize box are false.

**Comment by dannyparsons** [comment]
Yes that's exactly right and the form border style should be fixedtoolwindow so that the form is not resizable.

**Comment by maxwellfundi** [comment]
yeah. So we need to make sure all these dialogs need to be consistent

**Comment by maxwellfundi** [comment]
@dannyparsons this is also done
