### ISSUE TITLE
Scatter Plot Dialog does not have any current receiver when the dialog first opens

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/Instat#1703]

**Comment by maxwellfundi** [comment]
@africanmathsinitiative/instat this is fixed. Thanks.

**Comment by dannyparsons** [comment]
Thanks. Remember you can use 'Fixes #xxx' in your pull request description and it will automatically close the issue when it's merged.

**Comment by maxwellfundi** [comment]
Okay, thanks Danny. Will use that next time.

Thanks

Regards
Maxwell Fundi
|| Phone :+254728508241||
