### ISSUE TITLE
New Modelling Dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#1712]
This is the Model > General > Fit Model dialogue.  The task is first for John to organise the new dialogue.  Then for Steve to add the R-code to get it working.
The reason for the split in the tasks is that this dialogue has a calculator to specify the model, and John is now our new whizz on the calculator!  
So, John, you could start from a copy of the Model > Three Variables > Fit Model dialogue.  
Keep:
a) Data selector, etc on the lhs.
b) Response Variable
c) Everything from Distributions and Model Options downwards.
Now:
a) Replace the label "First Explanatory Variable" by "Explanatory Model"
b) Replace the receiver there by your formula receiver from your calculator.
c) Replace the controls and labels for the Model Operator and the Second explanatory variable, by a special keyboard that I describe below.

OK, now for your keyboard.  It has 2 parts (with 3 rows).  The first part has 4 keys across and looks roughly like this:
1.  + : \* /   (i.e. plus, colon, times, divide)
2. () (  ) ^  (i.e. Double bracket as in your caclulator, left bracket, right bracket, power symbol)
3. \- 0 Clear  (i.e. minus, zero, Clear, as in your calculator - can be double size)

The second part adds another two columns, but is slightly separated, perhaps by a larger space.  Then it takes 6 of the functions from your maths keyboard:
1. sqrt, cos
2. log, sin
3. exp, tan

As in your calculator, they would insert for example sqrt() with the cursor in the brackets.
Ideally your calculator could be used on either receiver.

I hope that is clear.  Danny may add to these instructions.  
Once the dialogue is done, the code behind to be added should be about as simple as for the other modelling dialogues.  There might need to be similar checking of the formula or error trapping, (just as in your calculator)  in case an impossible formula is given.

Thanks

Roger

**Comment by Lunalo** [comment]
Hi  @rdstern and @dannyparsons 

The dialog is now in place. @stevekogo  needs to carry on with it

Thanks

**Comment by dannyparsons** [comment]
Would this be easy to get working soon before the beta?

**Comment by maxwellfundi** [comment]
@Lunalo and @stevekogo  what is the status of this. Can it be closed?

**Comment by stevekogo** [comment]
This was addressed. It can be closed.
