### ISSUE TITLE
Addition to the modelling sub-dialogues

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#1713]
Steve,

There are currently 2 tabs in the modelling sub-dialogue called "Display Options".  For now we can keep this name, with the idea that saving some results means displaying them in the grid.
So, could there be a third tab, perhaps called **_Save_** which will save results back into the grid as further columns.  

There would be default names for the resulting columns.  They all are generated from the model object.
There could initially be 4 options, namely:
1. Fitted Values (Fitted) or Fitted1). R function is fitted(model)
2. Residuals (Resids or Resids1).  R function is resid(model)
3. Standardised residuals (Sresids or Sresids1). R function is rstandard(model)
4. Leverage (Lever, or Lever1). R function is hatvalues(model)

Thanks

Roger

**Comment by stevekogo** [comment]
Hi Roger,

I am going to get this working as soon as possible. For now, I am trying to
setup visual studio on a new computer then get back to work. Hopefully, I
will have something to share before the end on tomorrow.

Regards,

Steve

**Comment by maxwellfundi** [comment]
@stevekogo  was this fixed so that it can be closed?

**Comment by stevekogo** [comment]
Yes, it was fixed. It can be closed.

**Comment by maxwellfundi** [comment]
@dannyparsons this needs closing
