### ISSUE TITLE
Improved regression plots

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#1717]
Maxwell, please could you add the visreg package to R-Instat for the next version.
Steve, this package produces exactly the plots I have been searching for, with your regression models.
1. In the R code we can call visreg(...,gg=TRUE) instead of using ggplot directly.
2. In the sub-dialogue it will mean that the whole sub-dialogue will have to be larger to accommodate all the options we need. I don't see that as a problem.
[visreg documentation.pdf](https://github.com/africanmathsinitiative/Instat/files/471303/visreg.documentation.pdf)
[visreg.pdf](https://github.com/africanmathsinitiative/Instat/files/471305/visreg.pdf)
3. I suggest we start with the 2-variable sub-dialogue.
4. In the current options we keep the main checkbox, and also the checkbox for confidence intervals (this is the default **band=TRUE** argument. Keep also the confidence level, which is the **alpha** argument.  Drop the prediction intervals option.
5. Add radio buttons for "Plot Type" as "Conditional" or "Contrast". (Default is Conditional.)
6. Add radio buttons for "Residuals"  as "Partial" (Default), "Rug", and "Rugs". (This is the argument Rug, which is either FALSE, or 1 or 2.)
7. Radio button for "Scale", which is either "Linear" (default) or "Response".  This is the scale argument.  It is only for glms and is ignored otherwise.
8. A checkbox for "Jitter".  Default is not to jitter, and can be inactive for now.
9. An up-down control "White-space", with a default of 0.2 and going from 0.0 to 1.0 in steps of 0.1.

There will be more for the other regression situations, but that would be a great start for now.

**Comment by dannyparsons** [comment]
@maxwellfundi I will do the package installation this time as it's a slightly different process to what we did before. You could learn how to do this to do it in future.

**Comment by maxwellfundi** [comment]
Okay, thats fine.
You might need to show me how we are currently doing it.
Thanks

Regards
Maxwell Fundi
|| Phone :+254728508241||

**Comment by maxwellfundi** [comment]
@stevekogo  how about this? Can it be closed?

**Comment by stevekogo** [comment]
It was fixed. It can be closed.

**Comment by maxwellfundi** [comment]
@dannyparsons  close this as well
