### ISSUE TITLE
Fixing for maximise and minimise box on organise and model menus 

### ISSUE THREAD

**Issue by Lunalo** [africanmathsinitiative/Instat#1724]
Hi @dannyparsons , @stevekogo  @maxwellfundi  @stevenndungu ,

I am currently working on this dialogs.

I will let you know when am done.

Thanks

**Comment by maxwellfundi** [comment]
Good, @lunalo Describe is done!!

Regards
Maxwell Fundi
|| Phone :+254728508241||

**Comment by dannyparsons** [comment]
Thanks guys. Can you also check sub dialogs?

**Comment by Lunalo** [comment]
@dannyparsons  we are now working with @stevenndungu  on this. He is working on the model menu

**Comment by maxwellfundi** [comment]
Yeah, i can have a look at all the subdialogs in the project.

Regards
Maxwell Fundi
|| Phone :+254728508241||

**Comment by FrancoisJRenaud** [comment]
Going over all dialogues and subdialogues to check maximise and minimise + centered

**Comment by FrancoisJRenaud** [comment]
can be closed I think
