### ISSUE TITLE
Delete Columns/Rows Bug

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/Instat#1735]
The radio button for 'Delete Rows' is disabled.
Could this be enabled?

**Comment by dannyparsons** [comment]
@Lunalo Could you look into this. Deleting rows is working through right click in grid so should be possible in the dialog now.

**Comment by dannyparsons** [comment]
Current state of this?

**Comment by dannyparsons** [comment]
I seem to be able to delete a single row - not particularly useful but works on for now.

**Comment by dannyparsons** [comment]
Closing unless anyone thinks otherwise.
