### ISSUE TITLE
More in the Tools > Options dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#1742]
I have termed this to be a bug, i.e. that we can't yet save the options anywhere.
I would also like an enhancement, which could be called R-Options.  There may eventually be many, but I have just 3 for now.  They would each run the R options command.
My 3 options (so far) are: 
1. show.signif.stars = FALSE
2. width.  This is currently set to 80.  We may want to be able to change that, particularly as we can scroll in the output window.
3. digits.  The default is 7 and I would prefer less, say 4 or 5.  But happy that for some situations the user could then choose.

There are others, for example NA.action, and try to try formulae.

Thanks
Roger

**Comment by dannyparsons** [comment]
fixed by #2495
