### ISSUE TITLE
Mosaic package for R-Instat

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#1747]
Danny, could this package please be added?
Actually there are two packages, namely mosaic and mosaicdata.  It would be good to have both.  The mosaicdata package includes on dataset with many variables - over 200 I guess and it will be good to see how easily it goes into R-instat.
Thanks
Roger

**Comment by dannyparsons** [comment]
Done - `mosaicdata` data sets can be used for testing now as well.
