### ISSUE TITLE
More on residuals for linear models

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#1757]
Steve, although I suggested you here, perhaps one of the others can sort out the sub-dialogue?

The visreg package means we can have a separate tab for plotting the fitted models.
I would like a separate tab also for the "Residual plots"
We may need to experiment a bit, but I think the default can still be the four plots.  But one can have up to 6, and it can be useful to choose the single plots to look in more detail.  So here are the different options.  Only 1 to be chosen.
1. Four plots (default)
2. Six plots (3 rows)
3. Six plots (2 rows)
(then a line) to separate these from the "Individual Plots" - possibly that as the title)
4. Residuals v Fitted
5. Q-Q
6. Scale-Location
7. Residuals v Leverage
8. Cook's Distance
9. Cook's Distance v Leverage

This is the link that shows these examples:
https://cran.r-project.org/web/packages/ggfortify/vignettes/plot_lm.html 

Thanks

Roger

**Comment by stevekogo** [comment]
This has been fixed by #1767
