### ISSUE TITLE
New Dialogue for Model > One Variable > Choose Model 

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#1762]
1. Change the menu name from "Choose Model" to "Compare Models".
2. The main dialogue is very simple.  It has the "usual" selector control.  Only it is just for the "fitdist" objects that have been generated in the previous dialogue.
3.  There is a multiple receiver.  I am not sure whether to allow just a single object here.  If it makes the code more complicated, then insist there are at least 2 objects to be compared.
4. There is a "Display Options" button.
5.  Then just the usual Comment and OK controls.  There is no Save control here.
6. There could (perhaps later) be a further check on the objects being compared.  The command summary says that the set of objects will be considered as discrete if the first one is discrete.  In the object this is the 16th element.  Usually the objects being compared will all be continuous or discrete, so not a problem.  But if they are mixed, then the first object should be discrete, because that is what the software checks. 
7. I think the "system" also only works if all the objects are from the same data set.  The data is the 10th element of the saved object.  I hope this might be checked by the procedures, so we don't need to do it.  Let's see.

**Comment by rdstern** [comment]
This comment is to add the sub-dialogue.
This will be tabbed.  It calls 2 functions from the package.  One is gofstat for goodness of fit statistics.  This can be the main part of the sub-dialogue.  Fit would be a good name.  Then in the sub-dialogue it should say "Goodness of Fit Statistics".

The command to run for the goodness of fit is 
result=gofstat(list(savedobjects)).
This saves an object of type gofstat.fitdist.  

If it is printed, then it gives what it thinks are the important statistics.  For now we could do the simplest and add extra elements later.  But some of those extra elements are very nice.  So I am inclined to try to add them.

So we could have an option to "Save Object".
Then a checkbox to "Save chisquare to data frame".  This is the 5th element of the object and it would write a new data frame with 4 columns.
Then there could be a checkbox (default unticked) to "Input breakpoints for chisquare".  If ticked, then it would receive a list of numbers.  They should be in ascending order.  (When I didn't do that, then it gave me a silly answer, which was fine!  So we don't need to check that!)

The other is some plots.  The plots are described under graphcomp in the manual.

There are 4 graphs and they each have lots of options, so I am inclined to put each one on a separate tab. They are  "cdf", "density", "qq" and "pp".  Only cdf is allowed for discrete.

For now we could probably start with just a checkbox for each graph.  the default would be for cdf to be checked and the others to be unchecked.  We could later look at other options for the graphs.

Roger

**Comment by lilyclements** [comment]
I believe this issue can be closed
