### ISSUE TITLE
A simple count dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#1795]
This is a very simple dialogue, but one that will use a function we write.  The initial code is given by Sam and is below:

This isn't urgent, because I am not sure how we call a function in this way.  And I suspect we may need improvements - always do - when it is to be used generally.

It is a simpler version of the dialogue in Genstat, called "Fill by Groups".  Ours could be "Count in Factor".  It could be in the Column: Generate menu, below Regular Sequence.  there could be a line below that.
The dialogue is very simple.  The usual selector, with just factors displayed and a single receiver.  OK is enabled as soon as the receiver has a factor.
There is the usual "New Column Name" control and the default name could be "Count1" 

Here is the code from Sam:

data1<-data.frame(a=factor(c("a","b","c","a","b","b","a","c",NA,"b")),b=1:10)
countinfactor<-function(x){
  y<-rep(NA,length(x))
  for(i in 1:length(x)){
  y[i]<-ifelse(is.na(x[i]),NA,sum(x[1:i]==x[i],na.rm=T))
  } 
  return(y)
}
count1$c<-countinfactor(data1$a)
count1

**Comment by maxwellfundi** [comment]
@rdstern @dannyparsons  am happy taking on this task. 
Thanks.

**Comment by maxwellfundi** [comment]
@dannyparsons  Was the method for this done? the dialog doesn't do anything yet.

**Comment by dannyparsons** [comment]
No not yet, thanks for the reminder. I will get the method added soon.

**Comment by rdstern** [comment]
I have found the function.  In the dae package there is a command called fac.nested.  This does (I think) exactly what we need..

**Comment by maxwellfundi** [comment]
@dannyparsons  was this method created? What is its name?

**Comment by dannyparsons** [comment]
No but can you check the R function that Roger mentioned in the issue, if that works we may not need to write our own.

**Comment by maxwellfundi** [comment]
@dannyparsons  have been looking at this and researching and i think from our discussions here with @Lunalo  seems like we could use this function (fac.nested)  .

**Comment by dannyparsons** [comment]
Great, happy for you to try implement it now then.

**Comment by maxwellfundi** [comment]
Okay great.

**Comment by maxwellfundi** [comment]
We also need the help id for this dialog.

**Comment by dannyparsons** [comment]
What is the help id?

**Comment by maxwellfundi** [comment]
iHelpTopicID for the dialog

**Comment by dannyparsons** [comment]
Ok yes that comes in from the help.

**Comment by rdstern** [comment]
Thanks for asking.  The help topic ID for this dialogue is 457

**Comment by maxwellfundi** [comment]
Thanks Roger.

Regards
Maxwell Fundi
|| Phone :+254728508241||
