### ISSUE TITLE
Describe > One Variable > Graphics

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#1803]
We looked at this dialogue yesterday, when Beth visited.  These comments are now from David, Danny and Roger.

The title of the sub-dialogue is wrong.  Have something like OneVariableGraphOptions.
The 3 radio buttons from the display sub-dialogue move to the main dialogue:
This has the same radio buttons as are now, but with Facets first and Single as the last.  The label should have an "s", i.e. Single Graphs.
Facets should be disabled if you have a mixture of numeric and non-numeric columns.
Facets is the default.  If the set of columns contains a mixture and the setting is facet, then the option  moves to combine and facets is disabled.  If the columns change, so facets becomes possible, then facets is enabled again.

The sub-dialogue should work.  Currently the options are ignored.

In Graph Options have a bigger dialogue (if needed).  Just 2 tabs.  The first is called Types and contains 2 combo boxes, for "Numeric", "Other".
In Numeric the combo box containing 4 choices, namely the 3 as now, plus "Point Plot".  Default is Boxplot
In Other we have a combo box with currently 3 choices Bar, Pie, and Dotplot and with Bar as default.  (The pie needs something extra, because it is the same geom as bar.  Danny will add to this issue.)
The second Tab is called display (as now).

The tab should have space for more combo boxes.  

In the other tab (Display) we have  a checkbox "Specify Layout".  If checked then Number of Columns becomes visible. This is an up-down control, from 1 to the maximum of 10 and the number of columns and with 3 as the default.
The second is a checkbox saying Free Scale Axis for Facets.  This is always available, but is ignored in running the command unless facets are used.

**Comment by dannyparsons** [comment]
@maxwellfundi have a look at graph_one_variable method in R to see how this should link up with parameters. I need to make some changes now to the code because of the new sub dialog design e.g. factor and character parameters will be replaced with "other", and there will need to be parameters for further new options from the subdialog.
Maybe start with the design stuff and general linking of the sub dialog while I work on the R code.

**Comment by dannyparsons** [comment]
In numeric the graph options can now be: boxplot, dot plot, point plot, histogram, density plot, frequency polygon.

**Comment by dannyparsons** [comment]
Also, we've decided to change the label "Other" to "Categorical"

**Comment by maxwellfundi** [comment]
Okay, Well noted.

**Comment by maxwellfundi** [comment]
I also need the iHelpTopicID for this dialog too @rdstern

**Comment by rdstern** [comment]
The help ID is 412.

While you are there the ID for Describe > One Variable > Summarise is 410
Describe > Two Variables > Summarise is 414
Describe > Two Variables > Graph is 416
Describe > Two Variables > Tabulate (not there yet) is 415

Thanks

Roger

**Comment by maxwellfundi** [comment]
Now, these are all added.
@rdstern i have also created the dummy dialog for the tabulate. I wonder if
you have the desired design for it so it gets started.

Thanks.

Maxwell

Regards
Maxwell Fundi
|| Phone :+254728508241||
