### ISSUE TITLE
Menus, particularly Describe menu

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#1826]
I suggest improvements in the Describe menu.  This is initially for discussion rather than for immediate action.  Once agreed it should be easy to implement.

The new top level menu under **Describe** could become:

One Variable
Two Variable
Specific 
General
(Line)
Multivariate
More Graphs

Details of suggested changes are as follows:

0. Delete the 2-variable Correlate item.
1. Add a new menu item before **Describe > General**, which is **Describe > Specific**.
2. Into the  **Describe > Specific**, put all three items in the current **Describe > Table Dialogs**, followed by a line.  Then delete the **Describe > Table Dialogs** menu. 
3. Then add  the 7 **Describe > Graphics Dialogs** that are above the current line there, i.e. **Scatter Plot** to **Bar Chart from Summary** .
4. Add a new menu item **Describe > Multivariate**, below the first line, i.e. just above the current **Describe > Graphics Dialogs**. 
5.  Transfer the 3 items from **Describe > General**, i.e. from Correlations onward to this new Multivariate menu. 
6. In the **Describe > General**  have a line, and below the line have the 3 items from the current **Describe > Use Objects** menu.  That menu can then be deleted.
7. Change the Menu **Describe > Graphics Dialogs** to **Describe > More Graphs**.

**Comment by maxwellfundi** [comment]
@rdstern I could restructure this as soon as am done with current tasks.

**Comment by rdstern** [comment]
Sounds good.  I expected discussion and suggestions for improvements.  The fact there are none must mean that my suggestions were perfect, so go ahead!

**Comment by maxwellfundi** [comment]
Okay, thank you.

**Comment by maxwellfundi** [comment]
@rdstern  the current menu now looks like this:-

One Variable
Two Variable
Specific 
General
(Line)
Multivariate
More Graphs
(Line)
Use Graph
Combine Graph
Themes

So , i now need to know what your 4th point meant because the 8th point said i rename the Graphics Dialogs, to More graphs.  Did it mean i add the 7 dialogs into the main menu and not as a drop down items for More Graphs?

Thanks.

**Comment by maxwellfundi** [comment]
@rdstern @dannyparsons  the themes dialog is still a dummy dialog with nothing. It would be nice to get the proposed design.
