### ISSUE TITLE
GeneralForGraphics: ApplyOnAllLayers and IgnoreGlobalAesthetics check boxes

### ISSUE THREAD

**Issue by FrancoisJRenaud** [africanmathsinitiative/Instat#1931]
We have been testing several settings with @maxwellfundi, and we have a few concerns: 

-When ApplyOnAllLayers is ticked for some layer "Layer1", the content of aesthetic receivers in subsequently added layers (e.g. "Layer2") is like in Layer1 (which is sensible). However, when in Layer2, one ticks Ignore Global Asthetics, the receivers keep their content, but the displayed aesthetics are not passed to the layer parameters, which sometimes leads to empty mapping as the global aesthetics are ignored. Thus when ignore global aesthetics is ticked, the dialog shouldn't display aesthetics that are actually going to be written in the global aesthetics and not within the layer... How to get that is another question...
- Moreover, when we use a boxplot in ApplyOnAllLayers mode, without x aesthetic, the R syntax requires a double quote "" as x aesthetic parameter, which is then copied into x aesthetic receiver in subsequently added layers. This leads to major crash if we click ok, as that doesn't correspond to a variable name.
- Also, when we edit a layer "Layer1", coming from another layer "Layer2", the way the two check boxes are ticked doesn't correspond to the way they were ticked in "Layer1" before editing, but correspond to the way they are ticked in Layer2, or whatever last layer was edited before reopening the sdg ...

**Comment by volloholic** [comment]
These don't sound like concerns they sound like bugs that need fixing. Let us know if you need help.

**Comment by FrancoisJRenaud** [comment]
Yup, we just post here to have record and potentially help indeed... I remember @dannyparsons explaining that double quotes issues... was treated somehow in ucrGeomListWithAes.SetAes (line 80)

**Comment by FrancoisJRenaud** [comment]
About to finish this bug trio. Just the bug number 3 is also there fro dlgBoxPlot. Just mentioning here so that I don't forget to solve this.
