### ISSUE TITLE
Improvments in the Organise > Summarise dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#1963]
There are two changes I would very much like.  And ideally in time for use in Barbados next week.
1. Currently the summaries give missing values whenever any value is missing.  It would be good to be able (as an alternative) to calculate the summaries based on the values that are not missing.  I think this is na.rm=TRUE.  So could there be a checkbox on the main dialogue, with labels something like:  "Provide summaries when missing values are present.
2. The calculation of the summaries, i.e. the sub-dialogue has (in my view) two small issues.  First I would prefer that we get rid of the tabs.  The Numeric options could move to the main sub-dialogue and be in a labelled group box.  And the default could be for far fewer summaries.  I would vote for just the sum, count and count of non-missing.

Thanks

Roger

**Comment by stevekogo** [comment]
@rdstern I am going to handle this issue as soon as possible.

**Comment by maxwellfundi** [comment]
@stevekogo can @dannyparsons close this?

**Comment by stevekogo** [comment]
This can be closed. It was fixed.
