### ISSUE TITLE
Describe > One Variable dialogues

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#1982]
There are 2 dialogues, namely Summarise and Graph.

1) In Summarise I now like Steve's new sub-dialogue much more.
2) But it doesn't seem to work!  When I add max and min to the summaries it resolutely just gives me the default ones.

3) There is a similar set of issues in graph.  When I use the options and change to a histogram, it resolutely insists I still want a boxplot.  When looking at the code it doesn't ever seem to add the type of plot at all, so it is just giving the default of boxplot.
4) There is another aspect I would like our graph "experts" to consider.  When I use the survey data and just numeric variables it permits facets, but not combine (as an option).  Is this correct?  I wonder what combine might allow us to do that we can't do with facets.
5) Now a proposed enhancement for the graphics.  Could we please add "Violin Plot" to the numeric options.  Also you have "Point plot", what about Jitter?  This is (I think) simply a jittered point plot, but as it has a special name we could include that option.  
6) And a further suggestion would be to enlarge the list by permitting 2 layers for some of the plots.  Perhaps they could just be further options at this stage.  The obvious ones are Boxplot + Jitter, Violin+ Jitter and Violine + Boxplot.  (It might have to be a small boxplot).  Ofv course if this gets too complicated, then we might have to change the "system".  We might anyway want to have a few separate options like "Amount of jitter", "Width of boxplot".  If this means that the sub-dialogue becomes bigger, (even tabbed) then that is fine by me.

Roger

**Comment by maxwellfundi** [comment]
@rdstern i think you might be having an old version of R-Instat. I solved your third issue sometime ago. 
I could quickly add the Violin plot to add to the list. 

We @dannyparsons and @FrancoisJRenaud  will discuss about the facets and combine and other options you suggested for the graphs .

@stevekogo  I think will fix the summarise.

**Comment by rdstern** [comment]
This time I don't think I was using an old version, so that is interesting.  I was using the "new" version straight from Danny, and in Visual Studio.  So your recent improvments mustn't yet have been included.  That's an interesting issue in itself.

**Comment by maxwellfundi** [comment]
I have the latest copy and  the sub dialog works well.I wonder why it os not working for you. I suggest you could talk to Danny and find out which version you are using

**Comment by maxwellfundi** [comment]
The last version i find in our archive is the one i made two weeks ago. it might be what you are using. I can make a new installer today from the latest copy.

**Comment by dannyparsons** [comment]
I think we're almost ready for a new installer, but not quite yet.

@maxwellfundi This is One Variable Graph, not Two Variable Graph. On One Variable, the choice of geom on the sub dialog doesn't generally effect the output.

**Comment by rdstern** [comment]
I have now labelled this as an enhancement as well as bug-hunting.  

I found that these 2 dialogues are working much better now on the usual survey data.  I had some suggestions for enhancements, and thought I should try them also on a larger dataset.

So I opened the diamonds dataset from the library - ggplot2.  It has just over 50,000 rows.

a) I was pleased how quickly it opened.  
b) It has some ordered factors.  They are shown as ordered factors in the metadata, but not indicated in the dataset.  We could just call them a factor of course, which they are.  For now I have no problem if they are also labelled as "(f) - maybe in italics.  Or I suppose they could be "(o) for ordered?
c) That's not the initial bug though.  neither the graphs or the summaries ran for me.  I took all the columns.  The graphics said it doesn't work for ordered, and I was not so sure about the error for the summarise.
d) So I left out the ordered factors and just did the "numeric" type columns.  It still insisted on Combine and not Facets.  That's because the variable "price" is integer.  (Which is a special case of numeric., so it should have allowed facets.
e) When I omitted price then it insists on Facets.  I was happy it allows facets, but why can't I still have Combine?

I thought I would leave you to puzzle about the main bugs.  It also shows the value of trying the dialogues with a range of datasets.

And in my exploration for options below I came across at least one bug in the specific graphs.  I used dotplot for multiple columns and said I wanted histodot.  The error was as follows:

---------------------------
Error running R command(s)
---------------------------
External component has thrown an exception.

The error occurred in attempting to run the following R command(s):

diamonds_temp <- InstatDataObject$get_data_frame(data_name="diamonds")

ggplot(data=diamonds_temp, mapping=aes(x=variable, y=value)) + geom_dotplot(binaxis="y", method="histodot")
---------------------------
OK   
---------------------------


Now for some suggested enhancements to the one variable graphs.  The different options now seem to work well.  This is excellent in showing the different types of graph.  This can be built on in 3 ways:

a) Adding more types of graph.  In particular it is great here that the graph type "Jitter" is just a point plot with jitter, but has a different name.  And Violin will be good - as we mentioned before.  Perhaps there are a few more?
b) Adding a few combinations, i.e. 2 layers.  Box + Jitter is an obvious one and probably Violin plus Jitter. I would also like Violin + box, but possibly with a narrow (or skeleton) boxplot. Look also at Histogram plus Density.  These are also obvious options to include on the main dialogues for the specific menu.
c)  The third suggestion needs more careful though and practice - possibly also with the main graphics dialogues.  I suggest it would be good to allow a very limited number of options and also consider defaults that are not simply set by R.  The main one is that the default histogram has 2 many bins - at least for small datasets.  If we don't have options for users, then perhaps we should consider setting the number of bins a bit connected to the size of the dataset.
The amount of jitter is an obvious argument.  I also found the pie chart looked a bit odd for the factor columns and wonder what alternatives there are.

Roger

**Comment by rdstern** [comment]
I have now tried to look further at the diamonds dataset.

a) We do have to work with ordered factors better.  Changing an ordered factor into an ordinary factor does not work - nothing happens.  I can make it an ordinary factor by making it character, and then factor.  then the describe > One variable > graph dialogue works.  And reasonably quickly too.  I suppose it should with "just" 50000 observations, but I am pleased it does.

However, try changing the factor columns into dotplots.  They say they are "Counts" but they go from 0 to 1 only, so seem more like proportions.  But for the diamonds dataset they re all "full", i.e. up to 1 for all groups - so what are they doing?

Roger

**Comment by maxwellfundi** [comment]
@dannyparsons this could now be closed.
