### ISSUE TITLE
Improvement on Enter Dialog 

### ISSUE THREAD

**Issue by Lunalo** [africanmathsinitiative/Instat#1989]
@stevekogo @rdstern @dannyparsons @FrancoisJRenaud @stevenndungu 
We are about to edit the dialog so that the output whch comes as vector is equal to the length of the current dataframe.

The main concern is: If the output vector is lesser, should we autofill the remaining cells with NAs?
or should we replicate the above output?

What if the output is longer than the the number of rows? and when does someone produce the output which is longer than the dataframe length?

Please think about this and provide your  contribution?

**Comment by dannyparsons** [comment]
I think we agreed that this should be handled by the R method and not checked directly in the dialog.

Currently we do what R does by default. If the result is longer than the data frame length, it gives an error. If the result is shorter but a divisor of the length then it repeats the result to fill the data frame, if the result is shorter and not a divisor of the length then it gives an error.
So if you data frame is of length 10, a vector of length 2 would happily repeat 5 times, but a vector of length 3 would give an error.
We use an Instat object method so any functionality we would like is possible.

We may want different functionality in different dialogs? At the moment its most relevant to the Calculator and Enter dialogs. Should they behave the same?

**Comment by FrancoisJRenaud** [comment]
Writing an R method sounds like the best option indeed. Is that the sort of things that would be included in the R packages we would be writing in the future, mentioned in #1970 ? 

Just a little thing from what we discussed here: If we focus on months, the most common use of months would arguably require cyclic repetition, no matter if the number of rows is a multiple of 12. I don't know if that choice would fit with the other possible creations from Enter. In which case,  do we want the same behaviour for all vectors produced within Enter ? I can imagine that segregation within a dialogue is not very easy. Unless there is a tick button, or some other feature on the dialogue, that gives the opportunity to the user to choose between different behaviours ?

**Comment by stevenndungu** [comment]
Having  R Method, could help solve this. Yesterday and today i was trying
in consultation with Francois and John to try solve this.
This was my suggestion ...I don't know what you think about if it can be
used.
[image: Inline image 1]
where the right hand side of the equation should be replaced with number of
rows of the current dataframe.ie.
*length*(*vect*) = *nrow*(*dataframe*)
final ouput to be added as column should be *vect ;*the argument of length.
 this would perfectly solve issue - I have found it challenging  to
Implement it.
Steven

**Comment by dannyparsons** [comment]
Great you have been discussing this.
@stevenndungu I can't see the image but yes the checks would simply involve using length on the output. These checks should be in the R method and maybe in the dialog too. If you look at the regular sequence dialog, there are some checks being done there to produce a message about the output, very similar to what we are suggesting.

@FrancoisJRenaud Yes this would be part of the package. We have many methods already as part of the instat object which would be in the package. These checks would go in the existing `add_columns_to_data` method which you can see is run when you add a column.

**Comment by FrancoisJRenaud** [comment]
Ok, found it, I see. Also we can have a look at the regular sequence again tomorrow with @stevenndungu. About the R method editing, is this something you expect us to try implement ourselves ? @stevekogo from what I understood from the Skype call you are comfortable with this R side of Instat ? Should we discuss that with @stevekogo's help ? @maxwellfundi tells me that he doesn't feel comfortable supervising this.

**Comment by rdstern** [comment]
I went back to the original information about the Enter dialogue - see a "new Enter...".  I am not quite sure why a new thread was started.  There I suggested as follows:

"When this is run, then it should be as for calculate. But if the length is too short then it continues with NA. If the length is too long, then it truncates. It doesn't give an error in either case.

One possible enhancement (for later, but discuss with Danny) is from the regular sequence dialogue. This shows what the resulting sequence will be. That would be a great feature to add here. It is a little like the "Try" on the existing calculator."

**Comment by FrancoisJRenaud** [comment]
> One possible enhancement (for later, but discuss with Danny) is from the regular sequence dialogue. >This shows what the resulting sequence will be. That would be a great feature to add here. It is a little >like the "Try" on the existing calculator."

Yes we have been working on this with @stevenndungu and then I don't know what happened with it. We will rediscuss this tomorrow. 

> "When this is run, then it should be as for calculate. But if the length is too short then it continues with >NA.` If the length is too long, then it truncates. It doesn't give an error in either case.

Ok, I didn't realised this had been fixed already... sorry for the little internal communication problem.

**Comment by rdstern** [comment]
I am not sure it has been "fixed".  This was my original suggestion when proposing the dialogue.  Part of the confusion could be because this is in a new "Issue", while the original suggestion for the dialogue is elsewhere.

**Comment by dannyparsons** [comment]
I will close this and we continue on the existing issue for the Enter dialog.
