### ISSUE TITLE
dlgRowNameOrNumbers

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/Instat#2021]
This is under Organise - Data Frame - Row Numbers/Names where there are two small issues:

1. If you insert a new column name, it sometimes runs it with the name you did not give it
e.g. If you open up the Dialog, then change the column name to say, "new_column", the new column keeps the old default name first time.
Try again and it does your new column name.

2. If you click on the second radio button and put in one of your variables from the dataset then the code does not run and an error comes up.

**Comment by dannyparsons** [comment]
What is the error that comes up in 2?

**Comment by dannyparsons** [comment]
@lilyclements should be fixed now, can you check?

**Comment by lilyclements** [comment]
1. Is fixed
2. Has an error still:

![image](https://cloud.githubusercontent.com/assets/21180424/20038406/e6f62424-a42a-11e6-9f18-eec330837e87.png)

**Comment by dannyparsons** [comment]
"row.names must be unique" is the message, so that's an expected error if the column isn't unqiue.
In future we could prevent that but it detects it sensibly for now at least.
