### ISSUE TITLE
Null ref in RLink called by dlgDeleteRowsColumns when no data frame

### ISSUE THREAD

**Issue by FrancoisJRenaud** [africanmathsinitiative/Instat#2026]
When opening delete rows/columns without dataframe (very sensible, which is why this is probably not very urgent), the function in RLink: FillComboDataFrame was trying to run 
 cboDataFrames.SelectedIndex = cboDataFrames.Items.IndexOf(frmEditor.grdData.CurrentWorksheet.Name)
at line 122, but frmEditor.grdData.CurrentWorksheet is Nothing so Null ref and badam, crash !  

Solving proposal: Probably add a reality check for frmEditor.grdData.CurrentWorksheet in the RLink ? The objectif is to set the default selected index to the dataframe that's active, so I guess the step can be merely skipped if there is no dataframe. 

If I don't hear back and no one is working on RLink currently I m happy to implement that.

**Comment by dannyparsons** [comment]
Yes, you may have to check grdData IsNot Nothing before you check CurrentWorksheet as well.

**Comment by dannyparsons** [comment]
Is this resolved?

**Comment by FrancoisJRenaud** [comment]
Oups, no, will do it in a minute... Unless you wanted to edit RLink ? Can explore for  #2116 also.

**Comment by dannyparsons** [comment]
Go ahead if you can fix this.
On the graph window, that's a pop up from R so we don't really have any control over how it works. If anything it's a bug in the RDotNet package which we just import. I think it's just something we document, and it will be a non issue once graphs go directly to the output window.

**Comment by FrancoisJRenaud** [comment]
Sould be closed now
