### ISSUE TITLE
dlgInsertColumns

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/Instat#2045]
There are a few bugs with this dialog. I have changed a few of them so once these changes have been merged (I'll comment below when this has happened) then the following bugs need to be fixed

1. I froze a column and then inserted several columns. First time I pressed 'OK' on Insert Columns, it crashed and didn't add any columns.
Second time it worked, but if I tried to unfreeze the frozen column then it crashed
2. When I made changes in both 'rdoRows' and 'rdoColumns' and pressed 'OK', it crashed.

**Comment by dannyparsons** [comment]
There are definitely issues with freezing columns which I will look into. Are there issues when you don't freeze columns?

**Comment by lilyclements** [comment]
Yes, so if I asked to insert rows before the first row it gives the error:

---------------------------
Error running R command(s)
---------------------------
Error in self$get_variables_metadata(property = display_decimal_label,  : 
  Display_Decimal not found in variables metadata


The error occurred in attempting to run the following R command(s):

InstatDataObject$get_data_frame(convert_to_character=TRUE, include_hidden_columns=FALSE, use_current_filter=TRUE, data_name="iris")
---------------------------
OK   
---------------------------


![image](https://cloud.githubusercontent.com/assets/21180424/20031333/b57364ce-a36d-11e6-8109-7af049baecbe.png)

**Comment by dannyparsons** [comment]
Ok I think that's an R code problem. I'll look into it.

**Comment by dannyparsons** [comment]
@lilyclements should be fixed now, you could test this again

**Comment by lilyclements** [comment]
Yep it's fixed - I assume because you disabled the "freeze" option?

**Comment by dannyparsons** [comment]
Freeze was one bug and inserting rows before row 1 was separate bug. Both "should" be fixed now.

**Comment by lilyclements** [comment]
I see! Yes, both are fixed and working
