### ISSUE TITLE
dlgCountinFactor

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/Instat#2054]
Two things;
1. Layout - colons need to be added and it needs to be aligned
2. When running this dialog, it cannot find the function "fac.nested" and hence does not run.

**Comment by dannyparsons** [comment]
Maybe disable this menu item? Not sure if it's been worked on much or is urgent? @rdstern

**Comment by lilyclements** [comment]
I'll wait to hear from Roger and then disable it after the go-ahead!

**Comment by maxwellfundi** [comment]
This has been working. We may not have added the dae package and hence that error

**Comment by dannyparsons** [comment]
Is that the only reason for the error?

**Comment by dannyparsons** [comment]
Unfortunately I think we need to disable this dialog, as messing with the R packages now is not sensible. OK can be disabled with the user control box in the middle. Could someone do that?

**Comment by dannyparsons** [comment]
The dialog can still be enabled on the menu

**Comment by lilyclements** [comment]
I have a few dialogs I need to disable. Can I access the main form @Lunalo ?

**Comment by dannyparsons** [comment]
This doesn't need frmMain changes, just on the dialog

**Comment by lilyclements** [comment]
How do I do it on the dialog? I thought it could only be done through frmMain, sorry!

**Comment by dannyparsons** [comment]
It just needs OK disabled and the message.

**Comment by lilyclements** [comment]
Oh sorry, I thought you meant dialog disabled, I'll do that now!

**Comment by lilyclements** [comment]
Done
