### ISSUE TITLE
dlgRecode

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/Instat#2058]
This is under Organise - Factor - Recode Numeric where there are a few issues - but the main one is that it crashes the page

1. Layout - need colons added and things aligned etc
2.  If I add in break points, then I click to add labels and write something in - OK is not enabled.
3. If I then (after adding in break points and clicking to add labels with writing in it) reset the page crashes completely

**Comment by dannyparsons** [comment]
Can you look into seeing why it crashes?

**Comment by lilyclements** [comment]
I've had a small look and it's to do with the breakpoints having in it one item only. I'll have a deeper research tomorrow!

**Comment by dannyparsons** [comment]
I've updated the defaults in #2167 and I couldn't get a crash now. Can you re test and let me know how to get a crash if it's still possible. There are more serious changes needed so that less message boxes pop up, but that can be done later.

**Comment by lilyclements** [comment]
If I open it, put something in the selector and then write one number in the break points and press "ok" then it runs.
But, then if I re-open the dialog and press reset, it crashes.

**Comment by dannyparsons** [comment]
Thanks, investigating this with @stevenndungu now.

**Comment by FrancoisJRenaud** [comment]
solved isn't it ?
