### ISSUE TITLE
dlgReorderLevels

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/Instat#2063]
Under Organise - Factor - Reorder Levels, you can change the order of the levels. However, this does not actually work, the order of the levels within the factor remain the same.
Additionally, the layout needs work - colons, alignment, etc!

**Comment by dannyparsons** [comment]
What do you mean the order of levels remains the same? Seems to work for me.

**Comment by lilyclements** [comment]
Does it? If I move the order of the levels around it doesn't do it! That's strange!

**Comment by dannyparsons** [comment]
What are you expecting to see when you reorder the levels?

**Comment by lilyclements** [comment]
I thought it would re-order it on the data sheet? Is it not meant to?

**Comment by dannyparsons** [comment]
No it's not sorting the data, it's just setting an order to the levels of the factor column. So the order is used to do things like decide which order to display levels in in a graph.

**Comment by lilyclements** [comment]
Ah okay, sorry I didn't realise. I'll sort out the layout then and send it up!
