### ISSUE TITLE
Adding coord-flip to more of our graphs

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#2083]
The plotting is looking really good now - in general.  I have started using it to "solve problems" and have encountered some issues immediately.  This is to mention one of them in particular.  I initially just wanted discussion, but now feel that it would be good to have something done for the beta.

I hope that adding "coord_flip()" should be relatively simple and very useful.  We should have it as an option - at least for bar charts - and also for our one variable (and 2 variable?) graphs. 

I am using the ggplot2 diamonds dataset.  As it is the common example in the ggplot stuff by Hadley Wickham it would be good if we can do (with dialogues) what he does with the commands.

1. I used **Describe > One variable > Graph** with all the columns.  Hooray - it works.  And quite quickly too - and there are 50,000 rows of data.
2. As usual the factor labels on the x-axis overlap.  So here is my first problem.
3. It is more general than that.  How could I do vertical factor labels in general in ggplot2.  Now I know this is part of themes, but it is (perhaps) one of those features that we could make easy to do.  It is (as usual) an issue, and I give the code below.
4. Then I thought I could at least try it, with the ordinary bar chart, i.e. **Describe > Specific > Bar Chart** - I will use the variable called **cut** as an example.  For that I will just do **coord-flip**.  Oooh, I can't find it?
5. On boxplots it is on the main dialogue - called horizontal boxplot.  Where is it on our other plots?
6. I then though it would be fun to try a pie chart on the same data.  That is a boring pie chart - it is all grey!
7. Are there easy fixes?  
a) It is an "obvious" solution to the display of many labels in our **bar chart**.  If they are on the y-axis, then they are automatically at 90 degrees.  Hey presto.  We need this.
b) Could coord-flip also be added to the sub-dialogue for the one-way (and for 2-way?  If we do it very simply, then it would automatically apply to everything - and that is fine.  If it is tricky when we use combine (I am not sure why that should be so) , then could it at least be an option when we have facets.
c) I am less worried about the pie charts.  But I wonder if there is something I am missing here?

Roger

**Comment by dannyparsons** [comment]
For the beta I suggest:
1. Add coord flip to bar chart dialog
2. Add a blank "coordinates" tab to the general plot options, so that people can see it's coming.

**Comment by FrancoisJRenaud** [comment]
Ok I ll take care of that now, if no one is editing sdgPlots and dlgBar for the moment. 

-Should the coordinate-flip on bar dlg be called "Horizontal [bar chart]" as on boxplot or  something like "Flip coordinates"/"Coordinates flip" ? 
-Is it needed for histogram as well ?
-Should we leave the suggestion for one-var and two-var for later then or should @maxwellfundi work on these ?

**Comment by FrancoisJRenaud** [comment]
About the pie chart that is grey: the "fill" parameter in clsRaesFunction was removed by the SetSecondFactorReceiverParameter() in pie chart mode. Since this was called right after the SetFactorReceiverParameter(), which is assigning it's content to "fill" in pie chart mode, fill was never filled. Inverting the order of the call solved the issue.

**Comment by dannyparsons** [comment]
I think Horizontal as is on boxplots is fine. Start with just bar chart and then we can decide about others. Would be good to have on one and two var graph dialogs, if @maxwellfundi can do this. But it's not essential for the beta.

**Comment by dannyparsons** [comment]
Is this done?

**Comment by FrancoisJRenaud** [comment]
Not on one and two variables graph. I can work on this now if you want. I think @maxwellfundi was quite busy with installer stuff...

**Comment by dannyparsons** [comment]
If it's on Bar that's good enough for now. If there's time later we can add to 1 and 2 vars.

**Comment by FrancoisJRenaud** [comment]
Ok. I think the name on bar is still Flip Coordinates. Should I change to horizontal or is that fine ?

**Comment by dannyparsons** [comment]
I don't have strong views

**Comment by maxwellfundi** [comment]
I am now adding coord_flip for one variable graph

**Comment by rdstern** [comment]
Great.  Might you also add the other sorts of graph to the one-variable, or are you going to do a coord-flip on each dialogue in turn?

**Comment by maxwellfundi** [comment]
Yeah i am also adding the other things recommended as well as the combination of graphs. 

Thanks.

**Comment by rdstern** [comment]
If you are thinking of the other types of graph, then you may likeOver the weekend we found the sjPlot package to be "interesting".  It needs investigation.  But, in relation to the one variable charts I was excited by the sjp.frq procedure.  There are some examples here [http://strengejacke.de/sjPlot/sjp.frq/](url).
One feature I like is that the default in that procedure is to include the counts and percentages with each bar in the bar chart.

An interesting question - for research initially - is the extent to which is procedures integrate with ours.  Can we make use (for example) of his freq and still do our combine graph?  I also note that his options for "type" seem to cover most of what we have for both continuous and categorical.

Cheers

Roger
