### ISSUE TITLE
Disable options in specific graphs when multiple variables as factor used

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/Instat#2086]
To temporarily avoid bugs from #1215 and #1874, we need to disable both options buttons on all specific graphs, when multiple variables as a factor is in use. I have done boxplot as an example in #2085. Can others add the same code to the rest?
This should be in the release notes.

**Comment by maxwellfundi** [comment]
Great, i will get this done soon.

**Comment by FrancoisJRenaud** [comment]
Sorry @maxwellfundi didn't see your comment as I was working on this problem from #1874. Will be partially solved in pull request #2138. Still need to do rug and dot as these have been modified in #2107 which has not been merged yet.

**Comment by FrancoisJRenaud** [comment]
Ok I m finishing this for all the relevant  specific graphs in #2138

**Comment by FrancoisJRenaud** [comment]
Should close this now... was fixed by #2138

**Comment by FrancoisJRenaud** [comment]
Ok I m sorry, I thought I did it, but apparently I got confused. So forgot to disable option in rug and dotplot in the end... Can do it now for next beta release in december ... Should this be added to the bug list in release notes ?

**Comment by dannyparsons** [comment]
Yes we can add it to the release notes as a known bug.

**Comment by FrancoisJRenaud** [comment]
added to release notes and updated the pdf version in the R-Instat drive folder

**Comment by dannyparsons** [comment]
I had to undo this, as Roger had made changes to the original offline, sorry should have mentioned that before. I will update the original so you can add in the change again and re upload. Also, can you get Maxwell to upload as R-Instat, because now it has you as the author.

**Comment by dannyparsons** [comment]
I've shared the private folder, which contains the up to date Word version. Can you add to this then upload? And then transfer ownership to R-Instat.

**Comment by FrancoisJRenaud** [comment]
will do tonight
