### ISSUE TITLE
dlgMetadata

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/Instat#2087]
1. This dialog needs tidying up - colons added, things to be aligned, etc.

2. The code also currently does not work (This could be because of point 3.)

3. Additionally, what would we want to be able to input into the current value? It won't let me input anything but perhaps I am doing something wrong! @rdstern

Thanks!

**Comment by dannyparsons** [comment]
Current value is to show you the current value - you can't type in. If this is not working I suggest OK is disabled.

**Comment by lilyclements** [comment]
I see. If I put in the receiver items of the same type then the current value does come up.
e.g. for "Decimal" if I put in items with two decimals only then the current value of "2" comes up
Or for "Class" if I put in items from the same class
It then sometimes crashes - i've noticed with "decimal" then it tends to crash if one item is in the receiver.

The cbo box needs to be reset though for if I switch between the options at the top. E.g. If I am on say "decimal", select a value in the cbo box, then switch to "class" then it retains the value from decimal and you can press okay and it does not like that!

There's a lot of dialogs to go through still, so I think I will disable OK and put the ucr in on this one?
I can go back to it if I have time - or someone else can have a look if they do!

**Comment by dannyparsons** [comment]
Sounds like quite a bit to do. If we have time we can come back to it.

**Comment by dannyparsons** [comment]
Can this have OK disabled with the message in the middle?

**Comment by lilyclements** [comment]
I'll do that now

**Comment by lilyclements** [comment]
Just checked and it already has those features. This is for dlgMetadata right?

**Comment by dannyparsons** [comment]
Yes great
