### ISSUE TITLE
dlgScatterPlot

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/Instat#2101]
If I do a factor on scatterplot something strange happens (see picture).
Since it's a scatterplot I assume we do not want a factor to be an option for the variables (it can be an option for the "split by factor" of course!)

![image](https://cloud.githubusercontent.com/assets/21180424/20039042/81e32cc0-a435-11e6-9142-7ac81f85a57a.png)

**Comment by dannyparsons** [comment]
It looks like you've stacked some numeric columns with factor columns so you get one big factor on the y axis. Not very sensible, but is allowed. Factors in scatter plot can be useful e.g. try `ggplot(survey, aes(x = Village., y = Yield)) + geom_point()`

**Comment by FrancoisJRenaud** [comment]
Haha, looks like you are going through the same desire to avoid people to do silly things with ggplot @lilyclements ^^ I think Danny told me the "(Not very sensible) but is allowed [by ggplot so we keep]" about 15 times.
