### ISSUE TITLE
Links for the help file

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#2108]
I am finding some issues when inserting the correct link.
1) Dialogue NewWorksheer seems redundant and can be deleted.  The current one is called FileNew
2) Correct ID (6) for **File > New**,  (11) for (ImportDataset) **File > Open**, (156) for (FromLibrary) **File > Open From Library**
3) Convert seems live, but does nothing.  I thought there was some work on this.  I can't find a dialogue.  For now we should disable it on the menu.
4) need to think what to do with the save-as dialogue, because they are all the same!  Main one is 332 and that is now set.
5) Export dlgExportDataset doesn't seem to have an initialise procedure yet?

That's all so far in the File menu.

**Comment by dannyparsons** [comment]
Will try to sort these out with you and then get others involved if needed.

@stevekogo was anything done on File > Convert dialog? Not urgent for Tuesday but we will disable it if not there yet.

**Comment by stevekogo** [comment]
Nothing was done.

**Comment by rdstern** [comment]
Now the Organise menu.
On **Organise > Data Frame** all is OK down to Column Metadata which crashes R-Instat.
Rest now OK in that sub-dialogue
**Organise > Column Calculate > Calculations has some issues.**  
a) What has happened to the Text keyboard?  It could also be called "Strings (Character Columns)".  It used to be there.
b) Then there is Runoff - which should be called "Probability".  And the help actually goes to Runoff - which is fun!  Not yet fixed.
The rest of **Organise > Column: Calculate** seems OK.
**Organise > Column: Generate** seems OK
**Organise > Factor** was OK until Factor Data Frame - now added.
**Organise > Date** is now OKfor make date and use date.  The name of the dialogue for use date is DlgUseDate.  All the others are dlg.  There isn't much code, so should OK be disabled?
**Organise > Column: Reshape**  OK to Append, now added.  Also menu should change so Append is above the line.
Then I assume there isn't a subset dialogue - well there is, but it is the same as filter?  At least that's where the help goes?
Random Subset went to Subset.  Now corrected.
In the Data objects, check the position of the dialogues - one is odd!
In the Data Objects the only issue (so far) is the metadata dialogue, which goes to Colour by Property.  There isn't currently the right entry in the help file, and so much here is disabled I am leaving this for now.
The R Objects dialogues are OK

**Comment by rdstern** [comment]
Now the describe menu:
There is dlgSummary that is blank and I think can be deleted?
Ditto dlgOneSampleSummaryData?
Ditto dlgTwoVariablesTabulate?
Ditto dlgTwoSamples?
For One Variable: One variable Summarise is dlgDescribeOneVariable and ID 410 added.
And dlgOneVariableGraph ID 412 added
For two variables summary I changed the title at the top of the dialogue.  It should be Two Variables.  I added the "s" myself.  How brave.  **More seriously I think the code for the Comment takes the name of the dialogue as its default?  Could it instead take the text at the top of the dialogue.  Then that would be more under our control as the dialogue is improved.**
dlgRugplot corrected to 476.  (These dialogues all (so far) have the help line there, even if commented out, or incorrect.  That's making it easy.  Thanks.)
dlg Summary Bar or Pie chart.  Title corrected - a space inserted!
dlgCorrelations ID 186 changed to 421, Principal Components to 422 and Canonical Correlations to 423
dlgCombineGraphs changed to 431

I think they now all work!

**Comment by rdstern** [comment]
The modelling menu:
Show Model added help ID = 157
The One Variable Fit, Compare, Show were not centred.  So centred the dialogues.
The Compare Models has a bug on first entry.  It says "This name cannot start with _".  It then goes into the dialogue OK and any following use of the dialogue does not give that error.
For 2 variables Fit Model changed the help ID to 366
There is a bug in the use of the same help line in the 2-variable use model.  It does not understand "ucrBase".  I have commented out the help line for now.
Added the correct help codes 369 for 3 variable Fit and 385 for 4 variables.
4 variables fit has a bug that threw me out of Instat.  It is when I tried to load the dialogue.
Hence I have added the Bug label and the beta milestone.
The general regression has the help ID 371 added.
What will we do with the dialogues below the line.  I have not checked the help.  I suggest we disable the main menu entries?

**Comment by rdstern** [comment]
The climatic and options menu.

It would be good to have access to the OpenSST and also the climdex dialogues, even if OK is disabled.  

Steve, I have connected the help on those.  Could you write something that could be put there on those 2 dialogues.  We still need to fix on a style for the help.  For now anything you write will be good.

I suggest all the other dialogues be disabled.  I am relaxed about which menu items people can see.

In the Tools > Options dialogue there is a Help button, but it isn't the usual control.  We therefore need a bit of code to connect the help.  The help ID is 336.  Danny claims that is easy to do!  So I am adding Maxwell, John and Steven to the Assignees here.

**Comment by maxwellfundi** [comment]
Great, this will be good tasks for this afternoon over here. 
Thanks
