### ISSUE TITLE
dlgThemes

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/Instat#2117]
This is currently an empty dialog.
1. Is someone working on this at the moment for things we want on the beta
2. Shall I disable the form to go to this dialog?
3. SHall I leave it as it is?

**Comment by dannyparsons** [comment]
If it's blank I don't see why we need to open it. Roger is editing frmMain so hold off any changes on there.

**Comment by lilyclements** [comment]
Got it. I'll either change it myself later or @rdstern can disable it while he's on the main form

**Comment by maxwellfundi** [comment]
@lilyclements we still are not sure what to put there. Leave it disabled.

**Comment by lilyclements** [comment]
Okay thanks. I'll disable it once I know no one is using the main form. I have quite a few others I need to disable too

**Comment by maxwellfundi** [comment]
Okay great.

**Comment by lilyclements** [comment]
This has been disabled now
