### ISSUE TITLE
Toolbar buttons

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/Instat#2124]
Need to edit/disable/remove some toolbar buttons before beta. I suggest removing Excel buttons and getting Copy button to work.

**Comment by maxwellfundi** [comment]
@dannyparsons  i think them remaining disabled is better to show the people that they will eventually have functionality, other than removing them completely

**Comment by dannyparsons** [comment]
I'm only suggesting we remove the Excel button because I don't think we want it at all. Once we eventually want can just be disabled if not working.

**Comment by FrancoisJRenaud** [comment]
Will work on this now

**Comment by FrancoisJRenaud** [comment]
Ok the toolbars look good. I ve deleted the excel one. When you say make the copy button to work, do you mean make the paste button work as well ?

**Comment by dannyparsons** [comment]
Just copy - paste is complicated.

**Comment by FrancoisJRenaud** [comment]
Does it make sense to do this now (for the beta) as we can't paste anyway ?

**Comment by dannyparsons** [comment]
Do what exactly? I'm suggesting copy is enabled and working, paste is disabled.

**Comment by FrancoisJRenaud** [comment]
Ok, DONEZO. should I try to get the right click copy to work as well ?

**Comment by dannyparsons** [comment]
Should be already

**Comment by dannyparsons** [comment]
fixed by #2197
