### ISSUE TITLE
General - Fit Model (dlgFitModel)

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/Instat#2126]
This dialog is not yet fully working and there are several bugs.
Shall I put the ucr on it and disable the OK button for the beta release?

@rdstern

**Comment by lilyclements** [comment]
@stevekogo are you working on this?
Which modelling dialogs are you looking at out of interest? I'm happy to go over a few if you want. Let me know anyway and if so, let me know which dialogs so we don't have a conflict!

**Comment by stevekogo** [comment]
@lilyclements I was fixing the four variable but I will move to the general one in a short while.

**Comment by lilyclements** [comment]
Great. Once it's merged I'm going to just change some things on the layout if that's alright! I won't edit any of modelling until I check with you first!

**Comment by lilyclements** [comment]
@stevekogo Are you finished on Three Variable Modelling? I would like to give it a tidy up if so!
