### ISSUE TITLE
Climatic - File - Open SST

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/Instat#2127]
I'm not sure what we do and do not want in the beta release in terms of Climatic!

Judging from this one I feel we should disable the "ok" button and put the ucr in.
What are thoughts on it?

**Comment by dannyparsons** [comment]
This should work. @rdstern and @stevekogo could test with the appropriate data and then we decide.

**Comment by FrancoisJRenaud** [comment]
Just to mention, I got a major crash with this, trying to open an csv file with openSST (with no dataset open if that may change anything), my whole computer crashed severely. Had to restart by hand.

**Comment by dannyparsons** [comment]
The computation in R is quite intensive for this, so if the file was not appropriate for SSTs then it could have got very messy in the R code and caused that crash. 
@stevekogo if the R method can't do something sensible when the data is in the wrong format we may have to disable this for the beta.

**Comment by stevekogo** [comment]
I have OpenSST dialogue with other datasets and it seems to work well and return sensible error messages in the event of datasets with different format. @rdstern could advise further in case we need to disable the dialog since it is climatic.

**Comment by lilyclements** [comment]
We could put an error message at the top just for the beta to explain they have to use the correct dataset? It would be a shame to exclude it in the beta because of this crash.

**Comment by lilyclements** [comment]
Is anyone working on this dialog (OpenSST) out of interest? I want to fix some things such as the reset button and layout.
