### ISSUE TITLE
Climatic - Organise - Summary

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/Instat#2128]
As this dialog is currently blank, should I disable it on the main form? (once Roger is finished on the form)
I'm only checking in case someone is currently working on this dialog for the beta

**Comment by lilyclements** [comment]
Should I treat other blank dialogs on this menu in a similar manner?

**Comment by dannyparsons** [comment]
yes, just check with @Lunalo before editing frmMain
