### ISSUE TITLE
Dialogs to Disable

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/Instat#2142]
Tomorrow I'm busy in the morning. So at about 130pm GMT (430pm your time), but at that time I plan to access the main form to disable certain dialogs (as long as no one else is on the main form then!)
I'm going to list here dialogs I plan to disable. If anyone has any additions I should disable then please put them on this issue! Or tag me in the dialog so I can add it here as this way we can keep track for disabled things for the beta version.

Thanks.

**To Disable on the Form:**

dlgThemes - DONE

_**Under Model**_
Some of the "Others" under Model (ones which are empty dialogs) - To Check with @rdstern and @stevekogo once Steve has finished Models work for today.

_**Under Climatic:**_
dlgStartOfRains - DONE
dlgEndOfRains - DONE
dlgSpells - DONE
dlgWaterBalance - DONE
Summary dialog on Climatic
Models dialog on Climatic

_**Under File**_
File - Convert doesn't lead to a dialog so this can be disabled for now

**Comment by maxwellfundi** [comment]
I have disabled some of these. @stevekogo  is still fixing models so we might want to have a look at them later.

**Comment by lilyclements** [comment]
Excellent, thank you. We'll see what Steve has to say after he's done with them to see what we should and shouldn't disable in terms of models.

**Comment by lilyclements** [comment]
Thanks for disabling those four climatics and Themes.

We now need to disable on Climatic:
Climatic - Organise - Summary
Climatic - Models (since this doesn't lead to a sub)

**Comment by maxwellfundi** [comment]
@Lunalo  please disable this too as you are working on frmMain
