### ISSUE TITLE
Typo in the Instat Data Object in convert_column_to_type method definition

### ISSUE THREAD

**Issue by FrancoisJRenaud** [africanmathsinitiative/Instat#2145]
In the convert_column_to_type definition, line 982 in the "convert to numeric" case, there is eseself that should be self: 

``else if(to_type=="numeric") {
 ``     if(is.factor(curr_col) && (factor_numeric == "by_levels")) {
 ``       self$add_columns_to_data(col_name = col_name, col_data = as.numeric(levels(curr_col))[curr_col])
``      }
``      *!!!!!*elseself*!!!!!!!*$add_columns_to_data(col_name = col_name, col_data = as.numeric(curr_col))
``    }

**Comment by dannyparsons** [comment]
Thanks for spotting that.
