### ISSUE TITLE
Adding to the help menu

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#2168]
The current help "system" has 6 sections.

I propose that they be put into the help menu.  If agreed, then this could be done by anyone who is altering form main for other aspects.

The titles and links to the help file are as follows:
Introduction  (Help ID 0)
History and FAQ (Help ID 290)
Getting Started (Help ID 3)
Menus and Dialogues (Help ID 12)
R packages and Commands (Help ID 26)
Data Sets (Help ID 71)

They don't all lead to anything very exciting, but it is better than nothing, and I will be working on improvements.

I am assigning just Danny initially, and would like his go-ahead, before this is implemented.

Roger

**Comment by dannyparsons** [comment]
Yes I agree. @Lunalo Can you make these changes or assign someone to do them? The items don't go to new dialogs, they just go directly to the help pages Roger has mentioned.

**Comment by Lunalo** [comment]
I can work on this

**Comment by Lunalo** [comment]
@africanmathsinitiative/instat 

I am currently editing frmMain

**Comment by rdstern** [comment]
I am re-opening this issue to propose 2 more links from the Help menu to the Help file.

The first is called Spreadsheet and is above the entry for Menus and Dialogues.  It has Help ID 134
The second is "About R" and is above R packages and Commands - it has ID 133.  
I'd also like to start a section that calls some pdf files.  I have added 2 so far, see below:

So the full list is now:

Introduction (Help ID 0)
History and FAQ (Help ID 290)
Getting Started (Help ID 3)
Spreadsheet (Help ID 134)
Menus and Dialogues (Help ID 12)
About R (Help ID 133)
R packages and Commands (Help ID 26)
Data Sets (Help ID 71)
Guides > Case Study Guide (call pdf file)
             > Glossary  (call pdf file)
             > More to Come (entry not enabled)

**Comment by dannyparsons** [comment]
@maxwellfundi These are the lines needed to open the pdf files in the Guides menu. Can you/someone add it in frmMain now I have uploaded those files.

**Comment by maxwellfundi** [comment]
@dannyparsons  which lines?

**Comment by dannyparsons** [comment]
`Process.Start(Path.Combine(strStaticPath, "Help", [name of file]))`
