### ISSUE TITLE
Model > Probability Distributions > Show Model

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#2189]
I like the improvements.  But I am looking for issues - so here they are!  

1. There is a funny receiver in the dialogue - sort of for a third parameter.  I wonder what it is doing there?

2. I also tried with a gamma model and found that it does not seem to remember the previous settings.  It went back to Normal mean 0 variance 1.

3. It is still not saving in columns of the right name.  I was on quantiles with a new sheet and the values 1, 2, 3, 4, 5, 6 and it said it was saving in quant1, which it did.  They were silly numbers for quant1, but it coped.  Then I moved to prob and it changed the name to prob.  However it didn't save to prob, but overwrote the quant1 column.

On the column I have no problem if it keeps the same root - perhaps dist1, either way.  But could that be done so it doesn't overwrite?

I also wonder why the dialogue is quite so wide?

**Comment by dannyparsons** [comment]
I think this is fixed. Is it?
