### ISSUE TITLE
Initial test of the beta release

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#2203]
Here is my first draft text.  I am still not sure how and where our testers should be reporting?  And we also do need a system and people to respond to the comments that people make.  

**Version 0.1 or R-Instat 8 November 2016**

Welcome to the first beta version of R-Instat.  Some people will remember today as the date of the US Election, but it is also exactly one year since the end of our crowd sourcing campaign called the "African Data Initiative.  If you want to remind yourself what it was all about, then look again at the 3-minute video here [https://chuffed.org/project/africandatainitiative](url).  

So, to celebrate this anniversary, we have the first beta release of R-Instat.  As you look at this software we hope you will agree we have come a long way.  You will certainly see that we still have lots to do!  We now expect to update these beta releases about once a month and are aiming for Version 1 by July 2017.

We hope you will be keen to start and please report all your discoveries to us.  Here is what we suggest as an initial run-through.

**1. The Installation**.   
We hope it went smoothly?  Please tell us.  Currently it is only for Windows machines.  If you have a Mac or use Linux, then you'll have to make a virtual machine.  When it is installed you should see the screen looks like this:

[Fig. 1: Capture of initial screen - give the figure a title]

**2. A first task - looking at a probability distribution**

Almost all you do will need some data.  But we start with a dialogue that can be used without.  Go to Model > Probability Distribution > Show Model

Either just press OK, or (even more exciting!), use the drop down, with the data to try the example below:

[Fig. 2 Capture the screen with 0.5, 0.8, 0.9..]  On the other half, put the captured graph that results]
When you press OK you will see a graph - very briefly - and then it disappears!  It hasn't gone really.  If you hover over the icon for R-Instat you can get it back again and it should look like the one above.  That's one of our urgent improvements, namely to have more than one graph at a time, and to be able to display them in the output window.

**3. Making full use of what you have just done**

We are aiming for R-Instat to be accessible for beginners to statistics packages - but we assume you are not a beginner.  If you are, then omit this task.  Otherwise we assume you also already - or through our installation - have R and RStudio installed.  Then go to **View > Log Window**.  Copy the contents from the start at least down to the first line that says **mosaic**.  That may be all you have.  Then go into RStudio and paste the contents there.  You should get the same graph.

We hope that worked.  That's one thing we aren keen to encourage for more experienced users, i.e. that an analysis could start in R-Instat and finish in RStudio. Fo you, as testers, we also hppe that if (when) things go wrong, you could try the last commands in RStudio, or at least send us the R-code that was generated and which didn't do what you wanted.

**4. Back to R-Instat** 

Back in R-Instat we'll continue briefly with this same dialogue.  First get some data to use, by going to **File > New** and accepting the defaults.  You should now have a small empty data frame as shown below.  Go to Organise > Column: Generate > Regular Sequence and generate the sequence from 0.05 to 0.95 as shown in Fig. 3.

[ Figure 3 with 3 plots, first the small empty data frame, then the dialogue and then the data frame with the data]

Here is my first big bug in R-Instat.  I can't generate the data above with this dialogue.  Help - can anybody fix that?  skype me if you want details.

I'll stop this draft now, so you can look.  I hope you can try this so far and also prepare this document with the captured figures, in Word.

Then I'll continue later.  I am assigning you all, but choose who will work on these.

**Comment by maxwellfundi** [comment]
Currently working on stuff for installations. @Lunalo  has taken up the task. 

Thanks

**Comment by rdstern** [comment]
I am continuing.
**5. A little housekeeping**

Before getting another picture it would be good to tidy the small data frame we have.  First the name.  Go to the bottom of the screen and <Right-Click> over the name Sheet1.  You should get a simple menu as shown in Fig. 4.  Click on **Rename** and it opens a dialogue.  Type the new name as **Test Prob** and press OK.  It should tell you that names cannot have spaces as shown below.  So make it **TestProb** instead and press OK.

[Fig. 4]

Now we also get rid of the extra column.  So go to where it says data2, <right click> and then accept **Delete Column(s)** as shown in Fig. 5.

[Fig. 5 show the screen with the cursor over Delete]

It should check that you do want to delete this column - which you do, so proceed.

**6. Back to the Show Model dialogue** 

There is an easy way to return to a recent dialogue.  Go to the toolbar as shown in Fig. 6 and you see the last dialogues that were used.

[Fig. 6 the toolbar item should show 4 dialogues were used..  Then, it should be side-by-side with the new look at the dialogue that I describe below.]

Return to the **Show Model** dialogue. Untick the Enter Values checkbox and tick the Save Results, just below.  Then put the column called data1 into the receiver and press OK.  It should have generated a new graph, and also put the corresponding deviates into a new column in the data frame.  You could now try with a different distribution etc.  

**7. A second data set** 

Go to **File > Open From Library.**  Click on the From Package field and change to **ggplot2**, choosing the first example, namely **diamonds** as shown in Fig. 7.  You should see that a second **Help** button is now enabled, just below the list of datasets.  Click on that button to get further information about the dataset, as shown also in Fig. 7.  (It is the example used by Hadley Wickham, the author of ggplot2, for many of the examples in his documentation.)

[Fig. 7]

Now return to the dialogue, select the diamonds dataset again and press OK.  The dataset should open as a second sheet in R-Instat.  If you scroll to the bottom you will see it appears to have just 1000 rows.  However, now go to **View > Data Frame Metadata** and you will see, Fig. 8 that it actually has 10 columns and 53940 rows.  They are in an R-data frame and the sheet you see is actually just a window onto part of that data frame.  

[Fig. 8 with both the data frame and the column metadata]

Now go back to **View > Column Metadata** and you see, Fig. 8, some details on each of the columns in this data frame.

**8. Some graphs**

Go to **Describe > One Variable > Graph**.   Use <Right-Click> in the data selector to select all the columns and press on the Add button.  You will see (Fig.. 9) that the radio button changed from Facets to Combine Graph.  That's because the graph that is coming is for data of different types.  Some columns are categorical while others are numeric.  Press OK. to give the results shown in Fig. 9.

[ Fig. 9]

You can now return to this dialogue.  If you choose just numeric column, or just categorical, then you can use facets - where the y-scale is usually identical for each graph.  You can also opt for different graphs compared to box plots of bar charts.  

Finally for now try Describe > One Variable > Summarise to provide numerical summaries that parallel the graphs given above, see Fig. 10.

[Fig. 10]

That's the end of part 2!  I have also hit another serious bug!

**Comment by rdstern** [comment]
9. A more ambitious analysis

Go to the Describe > Multivariate > Correlations dialogue.  Use the diamonds sheet.  You will see that you could use any of the columns.  Just copy the first one across, i.e. carat.  You will see, that the factor columns are no longer available, just the numeric columns.  

Now it depends on the speed of your computer.  If it is reasonable, then copy over all the remaining columns, see Fig. 11.  Otherwise just copy 2 of them over.  Then choose the Options button and select the pairwise plot.  Then return and press OK.  It should produce the graph shown in Fig. 12.

We would, at this point like you to reflect on whether Fig. 12 is called a graph or a table?  The fact that these ideas have merged is one reason we have chosen, in R-Instat to distinguish between **Describe** and **Model** in our menus, rather than the more traditional **Graphics** and **Statistics**.

**Comment by rdstern** [comment]
Finally, before you start your exploration we add a few points about the current R-Instat.
1. You will have seen that we have come quite a long way, but still also have a long way to go.
2. We now look menu, by menu.
a) **File Menu** You should be able to import data from a wide range of software, thanks to the rio package, which we are using for import and export.  We have not fully resolved how to import value labels in SPSS and have yet to try this sort of thing from other packages.
b) **Different files**  We are reasonably happy with the way quite long datasets are handled, but not particularly (yet) with those that are "wide".  For example if you go to the Open from Library and open the rockArt dataset from the DAAG package, this has 641 variables and takes about 10 seconds (on some machines) for each dialogue to appear.  We will fix this problem for the next release.
c) **Spreadsheet Operations**  We are fairly happy with the way the spreadsheets are working.  They are just a window onto R, as you can see if you start with an empty sheet, and type in some data.  Every time you leave a cell, R-Instat executes the corresponding R command.  We have yet to sort out **paste**.  
d) **Organise menu** This is reasonably complete.  We have fair facilities for calculating new columns, for dealing with factors, and also for merging, stacking and unstacking data.
e) **Describe menu**  We can summarise data reasonably well, but have yet to tackle tabulation.  We have spent a long time on the graphics and still have to sort out the powerful aspects of themes.
f) **Model menu** We still have a lot to do here.  We are reasonably happy with the structure, of the menu, but there is a long way to go on the output from the fitting, from the range of mmodels we can process, and on choosing and using the models.
g) **Climatic menu**  We have done a lot of work, "behind the scenes" and also on general facilities, such as handling dates, that are needed for the climatic work.  We will continue to have a climate object, which is now a special case of our Instat object.  We expect to make quick progress and the next release will contain much that can be tested.
h) **Help menu**  There is a lot to do here.  We also plan for a series of short videos to explain a range of aspects concerning the use of R-Instat.

Now you are "on your own"!  We hope you enjoy playing with R-Instat and look forward to your reflections and information on bugs, etc.

**Comment by dannyparsons** [comment]
This has now been included in the release notes.

**Comment by rdstern** [comment]
![regular sequence in r-instat](https://cloud.githubusercontent.com/assets/11226469/20128704/f98a90d4-a641-11e6-9e5d-9cd16cc06cd6.jpg)

**Comment by rdstern** [comment]
Please can you send me the Word version of the release notes, so I can complete the capture of the figures and the text for the getting started part

**Comment by FrancoisJRenaud** [comment]
https://docs.google.com/document/d/1Pwd0RW4suLrt5rAgEg8TSctkMnXY41eYgXCG17Yb2CM/edit?ts=581fcba7#heading=h.s16g9godoaok

**Comment by FrancoisJRenaud** [comment]
Here it is (in previous message). The getting started section is called
Explore R-Instat with us. I guess it could be changed to Getting started if
desired.

Cheers,

François

**Comment by rdstern** [comment]
Thanks for the address.  I have had to download it to add the figures.  I couldn't see how to do that from the online copy.  I'll return it soon.

**Comment by FrancoisJRenaud** [comment]
In order to add the figures, place the curser within the text where you
want to insert the image, then go to *Insert *Menu and select *image*. Does
it work ?

**Comment by maxwellfundi** [comment]
This could be closed too. 

was from the earlier beta ersion release @dannyparsons
