### ISSUE TITLE
Graphics Correlations bug adds another issue too

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#2210]
We still need to fix the ggpairs bug.

That's become more serious, because I have now tried on the diamonds dataset and it is still running!  I think that is because of the huge number of levels of some of the "factors".  

But it highlights another, more general issue.  Namely I can't close the dialogue, yet, and hence I can't stop R-Instat.  Is there a way we can break out of commands when they are taking forever?

**Comment by dannyparsons** [comment]
Yes I will do this now. No we don't have an easy way - Ctrl + Alt + Del, but we can investigate after beta.
