### ISSUE TITLE
Main Form - Disable Dialogs

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/Instat#2213]
Is anyone on the main form or can I access it? @Lunalo 

I need to disable the following:
Model - Other (One Variable) - General
Model - Other (Two Variable) - Two Samples
Model - Other (Two Variable) - Summary Data
Model - Other (General)

**Comment by Lunalo** [comment]
@lilyclements 

No one is working on it.

You can go ahead and edit it

**Comment by stevekogo** [comment]
@lilyclements How far are you with this? Can I add you a more dialogues to disable?

**Comment by stevekogo** [comment]
@lilyclements , @dannyparsons I am going ahead to disable above menu items

**Comment by maxwellfundi** [comment]
This could now be closed i guess.
