### ISSUE TITLE
ucrReceiverMetadataProperty: wrong type for ctrActive (link problem I think)

### ISSUE THREAD

**Issue by FrancoisJRenaud** [africanmathsinitiative/Instat#2242]
When clicking on add Layer for the first time when opening the GeneralForGraphics dialogue, after doing testing on the specific plot for dotplot, got an error in ucrReceiverMetadataProperty: in the following sub
 Public Sub SetValue(strValue As String)
        If TypeOf (ctrActive) Is NumericUpDown Then
            If strValue <> "" Then
                nudParamValue.Value = strValue
            End If
        Else
            ctrActive.Text = strValue
        End If
    End Sub
End Class

ctrActive was indeed a NumericUpDown, and strValue not "", but then strValue was still ""bygroup"" which is a parameter value coming from binposition in geom_dotplot... I think this is related to the bug (can't find the relevant issue) : when editing a new layer (calling LayerOptions), the parameters on that new layer are filled like on the previous layer (previous use of LayerOptions), even though these parameters have changed !! Here the dialogue tries to give the value of a geom_parameter, probably stored in clsGeomFunction, to the receiver for another parameter of another geom (geom_boxplot).

**Comment by dannyparsons** [comment]
If strValue = "bygroup" then ctrActive should not be a numeric up down. This is either a problem with setting ctrActive, or in the definition of some geom parameter.

**Comment by FrancoisJRenaud** [comment]
I know, this will all be solved by #2237 now :) so excited about fixing one of these messy bugs !
btw don't know if the mentioning fixes #2237 in the title of the pull request works. I ve been doing it several times but It didn't seem to close the issue automatically.
