### ISSUE TITLE
dlgCalculator

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/Instat#2280]
(Enhancement)

For the calculator dialog, under "Statistics", the statistics it does are for the column as oppose to the row. So for example if you do the max(x), it gives the same value for all of the rows, i.e., the maximum number of the overall column is repeated for the whole new column.

I feel we could have the option of Row Statistics here as well. So, if you do the max(x,y), then you are given the maximum number between those two columns per row.
Similarly for min, cumulative sums, etc?

**Comment by dannyparsons** [comment]
We do have some of these options in the row summaries dialog. So it could be worth thinking about enhancements to that dialog, extra functions etc..

It is technically possible through the calculator if you did something like: `apply(data.frame(Field, Size),1,sum)`. Not very straightforward. But I don't know if we want to make that easier or just keep the calculator as column operations and row summaries for things like that.

**Comment by lilyclements** [comment]
Okay I see. I know it's possible elsewhere, I just feel that it might make it easier for the user if it is under the calculator as well since there are things like column summaries there? I found it confusing I couldn't get things like the mean there anyway but I suppose this could be learing more towards 'describe' rather than 'organise - calculate'?
