### ISSUE TITLE
Climatic - exporting data for CPT

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#2307]
I understand that the climate object can already expeort data in a form ready for CPT?  So David says this addition should be easy.  It would be great to have this feature, or at least have the dialogue for this.

My understanding is that this would take the data from 2 data frames  (or it might be a single data frame, plus the associated meta-data).  One data frame, or the meat-data, would have the location information and the other would have annual summaries.  These annual summaries would usually be the Y variables for CPT, though eventually I would also like the option to export the possible x's.  (If so, then we would be using the multiple regression part of CPT and then examining the output.

In principle we could become more ambitious and have the station data from multiple sheets.  However I don't want to encourage this approach now, because I suggest we should promote users looking at the data before throwing it at CPT.  That is so much easier in R-Instat if the data re in one data frame.  So, if data are in multiple data frames, then we need to merge/append in R-Instat first.

The data in this data frame could either be "long" or "wide" and we should be able to cope with either shape.

Our facilities for linking should be able to cope with getting the coordinates of the stations, once we have the main data frame.  So the initial part of the dialogue could either be as follows:

1) Just the data frame with the data to be exported.  There is somewhere a checkbox to ask if the data are in "Long" format or "Wide".  If long, then there are 2 single receivers - perhaps 3?  One is for the years, the second is for the stations and the third is for the data being exported.  It is possible that the Instat (or climate) object will "know" about the years and the stations.  In that case those columns can be filled automatically, once the data frame is chosen.

The second possibility is "wide".  Then there is still a single receiver for the year.  There is a multiple receiver for the data.  I assume then that (possibly via the name) it is the column metadata that gives the station information.  We need to disucss with David/Danny how this will work.

Then it is an export of an ASCII file.  We might have a checkbox to put a copy in the output window, or some window.  I would like users to be able to see what is being produced.  I don't think it could go into a data frame could it?

Roger

**Comment by stevekogo** [comment]
@rdstern I have created a dialog for exporting the data to CPT but @dannyparsons is yet to add create climate object dialog so that I can use climate object object method created by @volloholic to export data.

Should I just implement this without using the climate object method? This can be a temporary fix which I will have to address once the climate object is properly integrated.

**Comment by dannyparsons** [comment]
At the moment we are not having a climate object, we will just have climate metadata in the instat object. So you can implement it as a separate function.
