### ISSUE TITLE
Testing the climatic menu

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#2353]
This is starting to look really good.  I have been testing items ready for the discussions with Jim/Tufa tomorrow.  It could work like this - so far - but I note some items I have found.

a) An oddity first in **File > Open from Library** that might be easy to fix? I was looking at the **climdex pcic** package which is in the library.  When I look at any of the 3 data files there, the help on the data file doesn't work.  I think that is because there is only a single entry in the description of the data, even though there are 3 separate data files.  I hope this might be easy to fix.  The data files do open correctly.
b) The **Climatic > File > Open SST** now.  It still has the oddity that it goes straight to the dialogue to choose the file the first time the dialogue is used, and not afterwards.  I thought it might be because the file name is blank the first time, but it is still blank - with me, on subsequent occasions.
Still on this dialogue, I would like the option of showing this one.  Steve, do you have an example data set and/or instructions that we can use.  I assume we would usually have to be online for this dialogue?  If so, we could still have some local files as case studies, and for those who are not online. 
c) **Climatic > Organise > Use Date**  Every time there is an update I check to see whether this is functional so I can test it.  I don't mind if some options are still kept inactive.  What is the situation with this dialogue now?  In the Organise menu I can see the dialogue, but not use it.  I can't see it in the climatic menu.
d) Climatic Inventory Plot You sound as though you have been working on this.  Can you send details of an example or two I can try?
More later to come

**Comment by rdstern** [comment]
Now to the new climatic menu:
a) On Organise delete "..." from Events.
b) The last two items and the line below Events can be deleted.
c) On Describe delete "s" from Temperature, add **Sunshine/Radiation...**
d) Then a **line**, and then **General...**, then another **line**.
e) Then copy the two remaining graphs from **Describe > More Graphs**, i.e. **Wind Rose** and **Cumulative Distribution**. It is copied, i.e. they also stay under Describe - as now.
(As an aside I am keen to explore the use of your "Inventory" as a more general display of data, than just for climatic!  So we still want it under Describe, and it might also be copied to the One Variable and two Variable dialogues.  Might it be a good way to get an idea of the contents of long columns of data - possibly split by a factor?)
f) Change **SCF...** to **SCF Support**  Make a sub-menu with a copy of **Open SST** and **Export to CPT** followed by a **line**.  Then a copy of the 3 dialogues under Describe > Multivariate, i.e. Correlation, PCA and CCA.

**Comment by dannyparsons** [comment]
a) Can be fixed fairly easily but seems this is a special case where the name of the data set is not exactly the same as the name of the help file

b) I think this works the same as the general File > Open works. So it was set up to be consistent with that. We can change this behaviour though.

c) I think we can get this working on the general Organise menu by tomorrow. Will check with @stevenndungu 

d) This will be merged in a few minutes. It requires Year, Day of Year and Rain column. We couldn't yet get it linked up with the general options dialog so temporarily we added an optional receiver for facets so you could do the plots by Station.

@maxwellfundi should be able to sort out the menu in the morning

**Comment by rdstern** [comment]
If still more time on the menu, then on Climate > Models delete the "s".
Also add menu items as Climatic > Model > Extremes and Climatic > Model > Circular.  They can be before the Markov Chains item.

Roger

**Comment by maxwellfundi** [comment]
I am currently adding and removing thing you recommended. So this will be part of it @rdstern

**Comment by rdstern** [comment]
Could you make a few minor changes in the climatic menu.
1) Under **Climatic > Model** have 
a) "Extremes...", 
b) "Circular..." 
c) The existing Markov modelling with the sub-menu.

2. Under **Climatic > SCF** swap the Open and Export, so Open comes on top of Export.

3. Under Climatic > Describe drop "More" from "More Graphs" and add "..." to General.

Many thanks

Roger
