### ISSUE TITLE
Roger's list of possible topics this week

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#2375]
My list below is partly climatic, but also some items that are more general – and also that could be useful for the first overview video we have been planning.  I am also conscious that we are coming to the end of Francois’ time with the team in Maseno.

So here are some items – a whole mix!

1)	File > Open from Library.  When an item is selected, and the Help used, then can the item easily remain selected?  Then we just need to press OK to import it.  (Useful for the video.  Only if easy.)
2)	Grid with 1000 rows visible.  Is it easy to have something that indicates that there is more?  We have been discussing this feature for quite a time.  (Also useful for the video.)
3)	In the grid and Organise menu, the View feature is great.  It seems to be taking Stephen forever though.  In the **Organise > Data Frame > View** dialogue there remain bits to correct/improve.  I have given the suggestions in a separate issue.  
4)	The **Organise > Column: Date > Use Date** is still work in progress.  It looks OK, but never gets active so I can test it.  This is the first climatic one.
5)	In the Organise menu, what are the plans for the links and key column dialogues?  In relation to climatic, Steve says he has now sorted out the importing of SSTs and TAMSAT data into 2 sheets.  This would be good to discuss in reporting the progress on climatic.  Would these linking dialogues in the organise menu be a useful feature, both in general and to illustrate this aspect?
6)	Can the **Describe > One Variable > Graph** dialogue be returned to and corrected/improved?  This is another dialogue that seems to have eaten time.  It is good and important, but seems to be going on too long.  Issues now include the fact that coord-flip doesn’t work, and the default is still Violin + jitter instead of boxplot.  It would be good to also add improvements, including decreasing the amount of jitter, and adding items for the bar charts to be able to include added layers with counts and possibly percentages – and both - as further items.
7)	Is it a good or a possible time to move to the new version of ggplot2.2?  In the proposed video we use boxplots and the labelling of facets is better in the new version.
8)	In the **Describe > Specific > Boxplots** I have found it difficult to always get the plots I want.  For example changing the factor in the facets doesn’t happen unless something else in the sub-dialogue is changed.  I sometimes have to do a reset.  Can these issues be fixed easily, or are they all part of the major sub-dialogue change?.  If so, then can this sub-dialogue work continue to be a priority.
9)	In boxplots (and in other plots where an axis has factors with many levels the labels on the x axis are hopeless.  Please can the orientation (angle) of the axis labels be included as soon as possible.  I know this is also going to come eventually under themes, but it is also appropriate as an item in the axis tab – and (unlike most components of themes) it does relate to data!
10)	I would really like to get boxplots working well, because this is a very useful tool in the quality control (of climatic data). So adding jitter on the main boxplot dialogue would be good.  Also good to include Violin on the main boxplot dialogue (as an alternative, like we have pie charts on the bar chart dialogue).  I am happy to make it simple, so they are alternatives (as are pie and bar).  If you want both, then you do  it as an added layer.
11)	I think I saw that Francois is working on jitter and violin as additional geoms.  That’s great.  Please can it continue?  
12)	**Describe > Specific > Bar Charts**.  Is anyone working on the options for this dialogue?  Good to have the options here (on the main dialogue) to add labels with count, or percentage, or both.
13)	**Model > Probability Distributions > Compare Models**.  I still think it should be easy to get this dialogue working.  Can we do this one in the week?
14)	**Model > One Variable and Two Variables Fit**.  This still seems to be using quite a lot of Lily’s time, without making visible progress.  I would like to work with her in the week – or the week after – to “nail” this for the simple case.  The general option for one variable is also not working well and needs to be fixed.  For me it works the first time, but gives 2 plots that mess each other up.  Then it gives an error when used on subsequent returns to the dialogue.  
15)	**Climatic.**  There are still minor improvements to the menu.  I’ll list them as a separate github issue.
16)	**Climatic > Organise > Inventory**.  It is great that this uses ggplot now, but it still needs a lot of work to get back to where it was with the ordinary plotting earlier.  The dialogue also needs to improve.  Ideally it could make use of the standard sub-dialogue system.  Could this have some priority.  It is a very useful feature.
17)	**Climatic > Start of the rains.**  It would be good to make progress on at least being able to do this – and within a general framework, so we can report on this start of the work.
18)	Importing TAMSAT etc.  This is an example of importing gridded data.  Excellent.  I wonder if we could get some ENACTS data from GMet and show that these can also be imported.  That would be great to report.  Could we also import the satellite radiation data?  That should be possible, because we have the code from Ojo's AIMS project earlier this year.
19)	**Export**.  Could we also export annual data (with geographical data) for CPT?  I think Steve may have the code for this.

Howzat?  Comments please.  What have I missed?  How many months of work have I provided?

**Comment by stevenndungu** [comment]
This can be closed
