### ISSUE TITLE
Duplicate Column(s) dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#2425]
This seems an omission in the Organise Menu so far and (I guess) an easy thing to do.

It is important (at least for Version 0.3, partly because we don't yet have an Undo.  Some operations, like changing a factor to a variate can result in a column with just NAs - which is a shame.

In Genstat it is a simple dialogue as follows:

![image](https://cloud.githubusercontent.com/assets/11226469/21586189/d60b3c2c-d0c5-11e6-9c5e-e6216eb7807e.png)

For us it should be easy in R.  I think newcol = oldcol may be all we need to do.  It then adds the column.  Unlike Genstat - see picture - don't allow the type of column to be changed at the same time.  It just duplicates whatever type the original column is, and assigns a new name.

It could go in the Organise > Data Frame > Duplicate Column... and it could be the entry below Reorder Columns...

**Comment by dannyparsons** [comment]
So this dialog should only have a selector, single receiver and name for new column, with default being OldColumnName1 etc.

The function for the dialog is the add column instat object method. So you can do this as an R function, and not with the assign to.

**Comment by dannyparsons** [comment]
fixed by #2433
