### ISSUE TITLE
Order for selector right click menu

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/Instat#2442]
Below is the current order of the right click menu on the selector (Add all works nicely!).
The order looks strange though. I think Clear should be at the bottom, and Select All is not that common. Add selected is most common so I would suggest:
- Add Selected
- Add All
- Select All
- Clear Selected

Any thoughts? @africanmathsinitiative/instat 
![rightclickmenu](https://cloud.githubusercontent.com/assets/11214914/21642559/f4a7bd8e-d27a-11e6-9751-e3124bd0e674.png)

**Comment by maxwellfundi** [comment]
I suggest the drop down list would look like 
Select All
Add Selected
Add All
Clear Selection

And just to get this right, the Add All, what does it do? i would think it would Select All then Add Selected.

**Comment by Lunalo** [comment]
This is my suggestion
Select All
Add Selected
Add All.
Clear Selection
I do not have strong view on how it should look like.

**Comment by dannyparsons** [comment]
We don't have Ctrl + A yet but we should, it's easy to do, @Lunalo?

**Comment by Lunalo** [comment]
@dannyparsons 

Yes, I can implement that

**Comment by stevenndungu** [comment]
Ctrl +A is yet to be added. Was the Order for selector right click menu agreed on - seems not yet implemented?

**Comment by stevenndungu** [comment]
Sorry, Ctrl +A is in place.  Order for selector right click menu is has not been changed, otherwise the issue could be closed. Thanks

**Comment by dannyparsons** [comment]
Great. We can still change the order, but will close this now.
