### ISSUE TITLE
Right click menu 

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#2446]
I like the right-click menu now.  But there are some very small points to correct.  

1. In particular "Duplicate Column" and "Convert to Date" should each have "..." after them.  This is the rule when they call a dialogue.
2.  Put "Duplicate Column..." after "Rename Column..." in the right-click menu.
3. Put **Convert to Ordered Factor** just under **Convert to Factor**.    
4. Duplicate doesn't yet have an entry in the organise menu. It could perhaps go just under Calculations, in the **Organise > Column: Calculate** menu?  
5. Add an option on the dialogue - (radio buttons!) in a group, with label "Position of Duplicated Column".  This has 4 options "Beginning", "Before", "After", "End".  The default is "After".

**Comment by Lunalo** [comment]
Thanks, I will make those changes shortly

**Comment by maxwellfundi** [comment]
@Lunalo  is this now done?

**Comment by stevenndungu** [comment]
This can be closed. Its complete.
