### ISSUE TITLE
New Infill Missing Dates Dialogue.

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#2448]
This is in the **Organise > Column: Dates** menu and after the **Use Date** item.

It has the usual selector.  It has a single receiver with the label "Date", for the existing Date column.  Ideally it would only show **Date** columns.  Below that is a multiple receiver with the label "Factors".  This only shows Factors.

Once the date field is completed, OK is enabled.  Danny and David will then do the R code for this dialogue.  (Apparently it was in the "old" climate object.)  Their code should first check that the dates (and factors) are unique.

Ideally if a climate data set has been specified, then it would only show those data frames.  More generally, with a climate data set the date field should already be known and can be completed automatically.  And if there is also a station column specified, then this is also added into the factor receiver. 

This is quite an easy one - so the person volunteering will probably not do the next one - which is much more "interesting"!

**Comment by maxwellfundi** [comment]
Am now doing this task.

**Comment by rdstern** [comment]
Great.  Thanks.

**Comment by dannyparsons** [comment]
@maxwellfundi Can you now add the R code to this dialog? I have added the method in the instat object?

**Comment by maxwellfundi** [comment]
Getting it done now.
