### ISSUE TITLE
New Markov Chains Dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#2449]
This is another dialogue - quite complicated this time, where David and Danny will do the code.  I am suggesting all three of you again - who will volunteer for the "short straw"!

It is called **Fit Model** under **Climatic > Model > Markov Modelling**.  Get rid of the other menu items there.  Butr start with the dialogue.

This has the usual selector.

On the right-hand side are 4 single receivers.  The first is labelled "Station", then "Date", the third is "Day of Year" and the fourth is "Rainfall".  OK is enabled when all are completed, except Station, which could be left blank.  (Next to the Station is a combo box with the options "Exclude", "Separate".

Ideally (perhaps not yet) if the data frame is climatic then some of these are completed automatically.

Below there are two group boxes.  The first is labelled "Seasonality (Harmonics)".  This has 2 up-down controls with the first labelled "From" and the second labelled "To".  The limits are 0 and 6 and the default for each of them is 3.  OK is disabled if "From" is more than "To".

The second is labelled "Order".  This has 2 up down as the other, with From and To, and limits 0 to 10.  The defaults are 0 and 2.  There is also a combo box with the 3 options labelled "Markov Type" with the three options "Full", "Dry", "Both".

Below this is another combo box with the label "Interactions".  And the options being "None", "All", "Both".

At the bottom is a "Additional variables" block, with a multiple receiver, plus a combo box with options "No interactions", "Interactions", "Both".

Finally there is a Save Model checkbox and Field with default name.  This is only enabled when the To and From are equal and none of the combo boxes have "Both".  So we can only save when a single model has been specified.

And another finally is an include plots checkbox.

Roger

**Comment by dannyparsons** [comment]
@stevenndungu @Lunalo @maxwellfundi This dialog is really urgent, must be complete by tomorrow. We're working on the R code today, can someone start the dialog tomorrow morning?

**Comment by Lunalo** [comment]
I will do the dialog, tomorrow morning. Thanks

**Comment by maxwellfundi** [comment]
This could be done as soon as it is needed. Tomorrow morning is appropriate

**Comment by maxwellfundi** [comment]
@Lunalo Is this complete too?

**Comment by stevenndungu** [comment]
This is complete too. Could be closed.
