### ISSUE TITLE
Setup Loading dialog

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/Instat#2455]
The properties of the setup loading dialog need to be corrected. Start position, maximise disabled etc.

**Comment by dannyparsons** [comment]
Fixed by #2460

**Comment by dannyparsons** [comment]
I think we need to test these with multiple screens. We have centre parent and centre screen which are different when you have two screens.

**Comment by maxwellfundi** [comment]
Yeah, Its sad we have similar screens here. I suggest, due to screen sizes
changing, we could make this a child form of frmMain then we let the start
position to be center parent. This will take care of different screen sizes.

Regards
Maxwell Fundi
|| Phone :+254728508241||
