### ISSUE TITLE
New sub-menu for keys and links

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#2456]
This is called **Organise > Keys and Links** and it comes **below** the horizontal line, and just above **Data Object**.  (I assume this can be done by either John or Steven.)

There are 5 dialogue (With the help numbers provided in brackets.)

1) **Add Key...**   (504)
2) **View and Remove Keys...**  (505)
3) **Add Link...**  (506)
4) **View and Remove Links...**  (507)
5) **Add Comment...**  (508)

(Note the Add dialogues are all singular, e.g. **Add Key**, while the View and Remove are plural - i.e. **Keys**.)

Kalifa will provide (I hope) an initial **Add Key** dialogue.  For the other 4 you could start with a blank dialogue, but with the help number included.

**Comment by stevenndungu** [comment]
fixes #2456

**Comment by stevenndungu** [comment]
This is already complete. Could be closed
