### ISSUE TITLE
New Menu for Corruption!

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#2458]
Version 0.2 is also partly for "show", i.e. so potential users have a clearer idea where we are heading.

With that in mind we would like a Corruption menu.  It comes between **Climatic** and **Tools**. 

It has just 4 items for now (Help IDs after the name.

1) File... (499)
2) Organise... (500)
3) Describe... (501)
4) Model... (502)

Add a blank dialogue for each, with the help IDs.

Thanks

Roger

**Comment by maxwellfundi** [comment]
@dannyparsons  this needs closing now, its done
