### ISSUE TITLE
Menu changes - mainly climatic

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#2466]
I have made this as 0.1.1.  There are some bits that are easy and/or need to be for 0.1.1.  These are first.  Then there are more changes that I have put into an additional comment below on adding the links to the help and this could become 0.2, i.e. next week. 

1. **Climatic > Define Climatic Data** no longer connects to the dialogue.  We need that fixed as 0.1.1.
2. And easy one is to change the word **Organise** to **Prepare**.! This is in 3 places, namely the **main Organise menu**, in **Climatic > Organise** and now in **Corruption > Organise**.
3. The dialogue that is called under Climatic > Organise > Events > Extremes should move, so it is called under **Climatic > Model > Extremes**.  This one is therefore also enabled, and the other one is disabled.
4. In the **climatic menu**:
a) Put a horizontal line under **Climatic > File > CliData** (Move **Export to CPT...** to under that line.  Check it still calls the dialogue.)
b) Put a horizontal line under Climatic > File
c) Move the line that is now **below Climdex**, so it is now above it.
d) Put the **SCF Support** to below the bottom horizontal line, i.e. the line that is currently below **Model**. 
5.  Still in the **climatic menu**, delete the "..." from **Climatic > Quality Control...** . **Move** The **Climatic > Prepare > Inventory...** and **Display Daily...** to be under the **Climatic > Quality Control** menu item.  And add a third item, namely **Climatic > Quality Control > QC Procedures...**
6.  In the Climatic > Prepare:
a) Make the first item **Dates**, i.e. move that item up.  This should be an identical list to the main Dates menu.  So as it is now, with the new entry of **Infill Missing Dates...** added below **Use Date...**. 
b) Delete **Infill...**.  That's now included within the Dates sub-menu. 
c) Then the second item is **Transform...**.
d) Check that the items Inventory and Display Daily have moved, so are no longer there.
e) Add a new item **Climatic > Prepare > Climatic Summaries...** next. This is above the item called **"Events"**.
7. In **Climatic > Describe** change **More Graphs** to **Climatic Graphs**.

**Comment by stevenndungu** [comment]
Working on this

**Comment by rdstern** [comment]
This is a shortened form of the Help IDs for some of the new dialogues.  I hope this can be for 0.2.  There will be a "sting-in-the-tail", but that is in the comment below.  For now it should be simple.

a) Prepare > Column: Calculate > Duplicate Column ID = 512
b) Climatic > File ClimSoft ID = 329, CliData = 354 Export to CPT = 355
c) Climatic > Define Climatic Data, ID = 328
d) Climatic > Prepare > Transform, ID = 358, Climatic Summaries = 510
e) Climatic > Quality Control > Inventory ID = 359, Display Daily = 361, QC Procedures = 511
f) Climatic > Climdex ID = 190
g) Climatic > Describe > Rainfall ID = 408, Temperature = 424, Wind Speed = 429, Sunshine = 432, General = 478
h) Climatic > PICSA > Rainfall ID = 118, Temperatures = 479, Crops = 480
i) Climatic > Model > Extremes ID = 488, Circular =  489, Markov = 491

**Comment by rdstern** [comment]
This is for Version 0.3.  It is reported now, as we are on the help.

There are a number of dialogues that are repeated in 2 (occasionally even 3) places in the menu system.  They are therefore also repeated in the Help system.  Our plan is for pressing Help to take the user to the right place in the help system.  Hence the call to help for these dialogues must reflect where the dialogue is being used.  I understand this is quite simple?  I guess, however, that is will become a routine that is called for each of these cases, where the alternative numbers (or perhaps the Help ID - which is text, will be easier to use, rather than the help context, which is a number.

Roger

**Comment by stevenndungu** [comment]
Tasks assigned above have all been implemented apart from the last comments meant for version 0.3.

**Comment by dannyparsons** [comment]
On Climatic > Prepare the Tag is "Manage" which then changes the text at run time. So the Tag needs to either be removed or changed to Prepare.
I think that is the only remaining task.

**Comment by stevenndungu** [comment]
I have corrected that. It can be closed now.
