### ISSUE TITLE
Tools > Options work

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#2478]
In the Tools > Options dialogue it would be good to have an option on what is displayed in the output Window.  Thuis could go on the Output Window Tab.  Perhaps it could be a combo box with the Options:

a) Output only
b) Output + Comments
c) Output + Comments + R command(s)

The default is what is there currently, namely c) above.

If you have time could you also explore changing the number of significant figures displayed in the grid. This could be added to the **"Data View"** tab.
This is in base R, see https://stat.ethz.ch/R-manual/R-devel/library/base/html/options.html and I think is options(digits=n) where n can be between 1 and 22 (we may limit to 1 to 15).  The default is 7 and typing **options(digits)** resets to the default.

In the grid I think 4 is about right.  Once we have this option I don't mind starting with the default of 7 (for now).

Thanks

Roger

**Comment by maxwellfundi** [comment]
@rdstern that link is broken

**Comment by dannyparsons** [comment]
fixed

**Comment by stevenndungu** [comment]
@maxwellfundi is this finished or still in progress?
