### ISSUE TITLE
Final push to Beta Version 0.1.1 

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#2481]
This first part is also in an e-mail.  

As always we are working way beyond the "call of duty".  Many thanks to all.

Our aim is to continue the "tidying" this weekend, for Version 0.1.1 and then solidify the code next week as we produce Version 0.2.  This will involve finding and correcting bugs, completing tasks that are in progress, and (perhaps) even having time to add one or two more features that help us to show where we are heading.  

One further objective in producing Version 0.2 is because of the fundamental work that will then start, on the road to Version 0.3  By then we will only have custom controls on our dialogues (and also sub-dialogues).  This is a major change that will affect all dialogues.  There are 2 consequences of this (we hope) last big "under-the-bonnet" change in R-Instat.

1) Some dialogues will no longer work, even though they were OK in Version 0.2.  So, version 0.2 is a baseline, to help us fix bugs we introduce through this big change.
2) Some bugs we find next week will not be corrected if the process is too complicated, and will be rendered redundant, because the corrected code will change anyway in Version 0.3.  This will usually be  in complicated dialogues, for example with the graphics.

So, in the comments below are what I have found so far for Version 0.1.1.

**Comment by rdstern** [comment]
1.  I think Maxwell is already working on completing the Tools > Options  bit for the 3 ways to display the graphs.  Plus possibly other minor changes in the resolution/size of the graphs.  Having the graphs in the output window is a really great advance.
2. In **Climatic > Prepare > Dates** the items to **Make Date**, **Use Date** and **Infill Missing Dates** should call the corresponding dialogues.
3. In **Climatic > Prepare > Events** call it "Specific Events" instead.  Then add **Extremes** back under **Spells**, but with no dialogue called. 
3.  In **Climatic > Model > Extremes** call the Extremes dialogue that was moved.
4. In **Climatic > SCF Support** the 3 dialogues for **Correlations, Principal Components and Canonical Correlations** should call the same dialogues as in **Describe > Multivariate**.

**Comment by rdstern** [comment]
1. I thought the dialogue on **Prepare > Keys and Links > Add Key** was there and working?  But now it doesn't seem to be called again.
2. The other 4 dialogues are there.  Could you check that the Help number is called from each dialogue?  They are numbers 504 to 508 for these five dialogues.
3. This could wait till version 0.2, but it may be quick to do, and it would be fun to show it next week,  In is another addition to the right-click menus.  When in the row (i.e. on lhs of the grid) it currently says "Insert Row(s) Before", etc.  Before Filter could you add "Add Comment...".  There could also be another horizontal line, so it is in a little section by itself.  When you use this it calls the **Prepare > Keys and Links > Add Comment**  dialogue.
4.  If you do item 3 above then could you do the same when you right-click in an individual cell.  It could be the top entry there and we don't really need a horizontal line.  It calls the same dialogue.

**Comment by stevenndungu** [comment]
Tasks above have been done. This can be closed I guess.
