### ISSUE TITLE
The Tools > Options Dialogue

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#2524]
This is getting more useful now.  But:

In the Output Window Tab I 
1) Changed the size of the comment text and made it bold.
2) Made a similar change to the Output text.
3) Didn't try other options - but they should be tried.

In both cases they change very nicely in the dialogue, and the changes are remembered (at least within the same session) when I return to the dialogue.

But they make **no** difference in the output window.

I also note that had they made a difference I might later have wanted to set them back to their default.  That might be for Version 0.3, but we should also consider that issue.

**Comment by dannyparsons** [comment]
@maxwellfundi could look into this.

On the last point, there should be a factory reset button that sets everything back to our defaults.

**Comment by maxwellfundi** [comment]
Yeah, I will have a look at this soon, 

Thanks.

**Comment by maxwellfundi** [comment]
@dannyparsons you can close this as well.

Thanks
