### ISSUE TITLE
Copy Data Frame

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#2528]
When you right-click at the bottom of a data frame, then "Copy" is disabled.

Could it become enabled and go to the dialogue Prepare > Data Object > Copy Data Frame

It should automatically fill in the data frame that sent it there.

Could you also check that this is done by other right-clicks that call dialogues.  For example try with 2 library data sets, from ggplot2, namely diamonds and then economics.  When I right click on Rename it correctly went to the **Prepare > Data Object > Rename Data Sheet** and "Economics" is automatically filled in.  Good.

But  then I go back to the **diamonds sheet** and right-click again.  Lo and behold I go to the Prepare > Data Object > Rename Data Sheet with Economics still automatically filled in!

A related task, with both these dialogues is when you access them directly, i.e. through Prepare > Data Object > Rename Data Sheet or Copy Data Sheet
I suggest that the correct thing is for them to "know" the visible sheet and always start from there?  You may want to check this point.  It is what happens with the Filter dialogue, but most others return with what was completed before.  This might need some more general discussion - which relates perhaps to the new changes in dialogue structure.  Currently it seems inconsistent between dialogues.

**Comment by Lunalo** [comment]
I have discussed with @stevenndungu .

He will be working on this

**Comment by stevenndungu** [comment]
Yeah, am working on this one

**Comment by stevenndungu** [comment]
This is sorted out now, thanks @Lunalo
