### ISSUE TITLE
Rename Dataframe

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/Instat#2574]
If I have two dataframes, A and B.
Then I open "Rename Dataframe", and input:

Dataframe: A                New Name: B

I expected to delete dataframe B and rename dataframe A as "B". However, Dataframe A just deletes altogether.

(Then if I go to 'Delete Sheet' Dialog, I can delete two dataframes - 'B' or 'B')

**Comment by lilyclements** [comment]
So I've played around with this a little more. This renames the data frame as we would want.
However, it removes the data frame closest to the Right Hand Side.
So, we want to fix that it does not remove the data frame on the RHS.

Additionally, we should give a warning that "There is already a Data Frame named B open. Pressing OK will overwrite this Data Frame".
(Except that it doesn't overwrite that data frame, they're both stored there still. So, do we want to implement in that it will overwrite it? Or just not allow the user to rename a data frame as something already open.)

An observation I made through the CHIRPS work is that if I save it as an RDS and then reopen it later - all my previously "deleted-by-renaming" data frames (not data frames I deleted intentionally) come back, this time with a prefix.
So, I have A and A1.
Would you mind explaining to me how this has happened?

**Comment by dannyparsons** [comment]
I think the simplest solution here is to not allow renaming as an existing data frame - as we do for columns. I can put this check in the R method.
