### ISSUE TITLE
Define Climatic Dialog

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/Instat#2684]
This is similar to define climatic, but for data relating to corruption, specifically government contracts.
There should be 18 receivers on the right with labels:
Country
Procuring Authority
Procuring Authority ID
Award Date
Signature Date
Contract Name
Sector
Procurement Category
Winner Name
Winner ID
Winner Country
Original Contract Value
Procedure Type
No. Bids
No. Considered Bids
Country ISO
Foreign Winner
PPP Conversion Rate

They should go in some kind of scroll box so that the dialog doesn't become too long.

The dialog code should contain a similar Dictionary of key value pairs, one for each receiver. I can fill that in if it is set up.

The R code is not written yet but again it will be very similar to the define climatic method so that could be started as well, otherwise I can do it.

This is going to be for a demonstration so the design is really important! Receivers all in line, equally spaced etc. use the Visual Studio auto positioning tools for this.

**Comment by lilyclements** [comment]
@dannyparsons can this be closed?
