### ISSUE TITLE
Packages to Import

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/Instat#2697]
@africanmathsinitiative/developers any packages you need imported add to this list. I've got a small list already comprising of

ncdf4
EnvStats
signmedian.test

**Comment by rdstern** [comment]
I suggest we will soon welcome **sjmisc** partly to enhance importing from Stata and SPSS (with labels).
And **sjplot** which competes well (I think) with stargazer for the display of tables, etc in our new enhanced output window.

**Comment by maxwellfundi** [comment]
@dannyparsons  i would like Hmisc package to be added for the One Way Frequency Dialog to do weights.

**Comment by dannyparsons** [comment]
Ok will add this in next time
