### ISSUE TITLE
Define Corruption Outputs

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/Instat#2735]
New dialog for corruption. Just has a selector and a multiple receiver.
Method not written yet but will be instat method `define_corruption_outputs`.
Parameters: `data_name` and `output_columns`
It should also have a way of having some columns already in the receiver when the dialog opens - as we have on other dialogs that open from right click menus.
This is quite urgent for tomorrow. Could someone do it in the morning? I can take over later if needed.
[SKM223 HP R17030118270.pdf](https://github.com/africanmathsinitiative/Instat/files/812162/SKM223.HP.R17030118270.pdf)

**Comment by lilyclements** [comment]
@dannyparsons I think this can be closed now
