### ISSUE TITLE
Fit Model Dialog

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/Instat#2736]
New dialog for corruption. It has a selector, a single receiver and two multiple receivers. Also a "preview model" label and read only textbox and a save model control.
The method will be standard R's glm or lm depending on column type. When the "corruption output" is a logical column it's glm and lm when it's numeric.
Labels for receivers are "corruption output", "control variables" and "indicators"
It should also have a way of having some columns already in the receivers when the dialog opens - as we have on other dialogs that open from right click menus.
[SKM223 HP R17030118280.pdf](https://github.com/africanmathsinitiative/Instat/files/812172/SKM223.HP.R17030118280.pdf)

**Comment by lilyclements** [comment]
@dannyparsons can this be closed now?

This dialog is complete, and is linked to the sub dialog used in other modelling dialogs
However, the sub dialog is not updated to the new system yet.
