### ISSUE TITLE
Define CRI dialog

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/Instat#2737]
New dialog for corruption. Picture below and I can explain in more detail.
[SKM223 HP R17030118281.pdf](https://github.com/africanmathsinitiative/Instat/files/812176/SKM223.HP.R17030118281.pdf)

**Comment by lilyclements** [comment]
Do you mean something along the lines of this:

![image](https://cloud.githubusercontent.com/assets/21180424/23503340/4719fc46-ff33-11e6-9fc4-b8f9eeb4fa4b.png)

Also, I can't fully read your handwriting, apologies. In the Red Flags listbox it says "Second Column gives weights - ? with corruption output"
And at the bottom it says "if flag numeric/binary then replace grid ____ a ____  _____ field limited to 0-1"

**Comment by dannyparsons** [comment]
Yes that looks good. The grid can be a factor grid instead of a standard grid. (Not sure if that is already)

If flag is numeric/logical then replace grid with a numeric up down, min = 0, max = 1. With label "Weight".

In the list box two columns, one for red flag one for weights. I could add the code once it's done as I haven't written it yet.

**Comment by lilyclements** [comment]
@dannyparsons I think this can be closed now
