### ISSUE TITLE
Define Red Flags

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/Instat#2738]
New dialog for corruption. Just has a selector and a multiple receiver.
Method not written yet but will be instat method `define_red_flags`.
Parameters: `data_name` and `red_flags`
It should also have a way of having some columns already in the receiver when the dialog opens - as we have on other dialogs that open from right click menus.
This is quite urgent for tomorrow. Could someone do it in the morning? I can take over later if needed.
[SKM223 HP R17030118290.pdf](https://github.com/africanmathsinitiative/Instat/files/812179/SKM223.HP.R17030118290.pdf)

**Comment by lilyclements** [comment]
@dannyparsons Can this issue be closed?
