### ISSUE TITLE
Describe > Two Variables > Summary

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#2762]
I wonder what has happened to this dialogue?  Could someone please check and correct.  I think Steve was involved earlier.

Once the bugs are fixed I suggest we swap the receivers.  Make the first one a single receiver  "First Variable" and the second should be the multiple receiver.  But perhaps check what is happening first, before changing this.

I tried with the diamonds dataset.  With first receiver a set of factors and the second a variate.  I got nothing   I wonder if it is in the middle of being updated to the new system.  Or is it the problem again that these are ordered factors?

I also got nothing with them the other way round.

Then I tried with 3 variates and got (I think) correlations.  So that's OK.

Then I tried with just factors.  But it insists that nothing has changed and gives me the correlations again.

So I tried by opening the survey data set.  But it will not clear the idea it now has to just give those damn correlations from the diamonds dataset.  So I gave up!

This needs a careful lookup and then some testing.

Thanks

**Comment by stevekogo** [comment]
@rdstern This is possibly the problem with the ordered factors which I fixed in the previous issue. I will have  a detailed look then get back to you.

**Comment by stevekogo** [comment]
@rdstern The bugs are bow fixed and the dialog seems to work fine like it used to before the new system was implemented. I will now go ahead and swap the receivers as you mentioned.

**Comment by stevekogo** [comment]
@rdstern What is the main reason for swapping the receivers? I hope we will still perform the same summaries w.r.t the column types.

**Comment by stevekogo** [comment]
Initially, having numeric columns in the multiple receiver and factor column in the single receiver resulted in summaries by factor. Will this still be the case upon swapping the receivers?

**Comment by rdstern** [comment]
The main reason is simply that the idea is that there is a particular column of interest.  And this is to be examined in relation to various other columns.  It just seems more logical to put the single column first.  The analyses stay as before.

**Comment by stevekogo** [comment]
What happens to the multiple receiver, do we still need to restrict it to
columns of the same type?

**Comment by rdstern** [comment]
Yes.  Just the same as before.
