### ISSUE TITLE
Deleting linked sheets bug

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#2812]
I did start of the rains and it worked OK.  Then I deleted the summary sheet.  I then did a dry spells dialogue (and again tried the start of the rains) and it gave the error below.  David claims this is because the linking information is not being deleted when the sheet has gone?

I now tried deleting also the initial Dodoma sheet - so I don't now have any sheet open in R-Instat.  I now found (to my pleasure) that the dialogues to make dates etc was still completed.  But the bug is the same.

I now (David told me to) renamed Dodoma into Dodoma2 and it still gives the same problem - and still recognises the dialogues as having been used.

I now tried to look at the links, and cannot use the View and Remove Links dialogue.  It gives me all the columns in Dodoma, but I can't do anything with them.  We will check this separately and possibly report as a separate issue.

RDS 

---------------------------
Error running R command(s)
---------------------------
Error in self$get_data_objects(data_name) : Dodoma_by_Year not found

The error occurred in attempting to run the following R command(s):

InstatDataObject$apply_instat_calculation(calc=instat_calculation$new(sub_calculations=list(instat_calculation$new(function_exp="cumsum(rain_day)-cummax((rain_day==0)*cumsum(rain_day))", sub_calculations=list(instat_calculation$new(calculated_from=list("Dodoma"="Rain"), save=0, result_name="rain_day", type="calculation", function_exp="match(Rain>=0&Rain<=0.85,1, nomatch = 0)")), type="calculation", result_name="Dry_Spell", save=0)), result_name="Max_Length", save=2, type="summary", function_exp="max(Dry_Spell)", manipulations=list(instat_calculation$new(type="filter", calculated_from= list("Dodoma"="doy_366"), function_exp="doy_366>=1 & doy_366<=366"), Year_Group_Daily)))
---------------------------
OK   
---------------------------

**Comment by dannyparsons** [comment]
That's right and I can fix this.

**Comment by dannyparsons** [comment]
I've made changes to fix this. It works well for the column summaries dialog but haven't tested for the start of rains dialog. Maybe @lilyclements could check this for those dialogs?
