### ISSUE TITLE
Make date bug

### ISSUE THREAD

**Issue by stevekogo** [africanmathsinitiative/Instat#2825]
Making a date column with Year and DOY seems to bug. @stevenndungu  should have a look at this.

**Comment by stevenndungu** [comment]
Thanks @stevekogo i see the bug. I was checking on it and the code generated looks similar to what was there in the previous version where it was running well. I remember @Lunalo  testing that section. I guess the R method has a problem may be - I will be looking at it in details with consultation.

**Comment by rdstern** [comment]
[METADATA_RAINFALL_GUYANA.xlsx](https://github.com/africanmathsinitiative/Instat/files/858869/METADATA_RAINFALL_GUYANA.xlsx)

The Make date seems to have regressed.  It now has fewer options than I remember before.  This is for transforming a single date column into one that R recognises as a date.

The data I have, is from Excel and is attached.  The date format is day/month/year which I am sure we could do before?  there now seem to be very few options and no possibility of saying the format in any way?  So I am unable to transform the dates in the attached file into proper date columns.  (I have been able to split the columnh as provided - with 2 dates, into 2 separate columns)

**Comment by rdstern** [comment]
I tried that.  You have 3 options including Year/Month/Day and Day-Month-Year, but not Day/Month/Year

**Comment by stevekogo** [comment]
@rdstern I have fixed the bug that I identified in the dialog and I intend to proceed adding more options to the combo box for specifying date format in the case of converting one column. Upon consultations with @stevenndungu we noticed that probable options and quite many. What is your opinion on what should be added to the combo box?
