### ISSUE TITLE
Changing the climatic menu

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#2971]
This is the first of issues today on further improvements to the climatic system.  I am timing this for the start of Danny's visit.  It is all part of "Steve's domain", but I suggest he will be able to use some help.  I am therefore suggesting Shadrack, but there may be discussions in Maseno on the best strategy.

This initial issue is on the climatic menu:
In general I would like to avoid menus "going too deep", unless absolutely necessary.
In the climatic menu therefore
a) Move the Dates menu up a level, so it becomes **Climatic > Dates**.  It remains below the line, (so it is still part of the "Prepare" group, and is just above **Define Climatic Data...** .
b) In **Climatic > Prepare** add a line below **Climatic Summaries...**
c) Move all the 5 items in "Specific Events" up one level, so they are below the line in **Climatic > Prepare**
d) Delete the now empty menu item called **Specific Events**.
e) Change the name "Water Balance" to "End of the Rains".
f) Delete the "other" "End of the Rains", which is just below.

**Comment by shadrackkibet** [comment]
This is good task for me i will be happy to discuss this with @dannyparsons and @stevekogo when they will be in Maseno before i implement it.Thanks.

**Comment by stevekogo** [comment]
@shadrackkibet Thanks for volunteering to fix this. As you mentioned, let's do this at the beginning of next week.

**Comment by shadrackkibet** [comment]
@dannyparsons .I think this issue should now be closed.
