### ISSUE TITLE
R-Instat Bug

### ISSUE THREAD

**Issue by shadrackkibet** [africanmathsinitiative/Instat#2981]
1)I was using R-instat and noticed that when you load the data set and then highlight all the columns and then delete all once, then it breaks. 
![image](https://cloud.githubusercontent.com/assets/26301973/25489653/24b40d60-2b73-11e7-9810-a9a1781e78ae.png)

**Comment by dannyparsons** [comment]
This is great testing. This is just the sort of thing we need to be trying consistently. I think @lilyclements has reported this bug already though somewhere. I will look for it.

**Comment by dannyparsons** [comment]
Can't seem to find it. @lilyclements I remember you noticed this but not sure it ever got written up?

**Comment by lilyclements** [comment]
I know when I found this bug it was by changing the width of a columns beforehand, and then when I added a new column by a dialog, it did something similar to this. I'll try and find the bug

**Comment by lilyclements** [comment]
I went to write it up and noticed it had already been written up - #2272 
It occurs when all the columns are deleted - so can happen if you delete just the last column.

**Comment by dannyparsons** [comment]
Thanks, will close this one then. I will try to remember to fix this, it is a fairly simple addition to the R code.
