### ISSUE TITLE
New Sheet Button on Workbook Tab does not create a new sheet through R

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/Instat#883]
The * button on the Workbook tab of the editor inserts a new sheet to the workbook but isn't doing this through R. 

It should either open dlgNewWorksheet or run the R code to create a new sheet with a default size.

**Comment by deaspo** [comment]
Can we disable it entirely? @dannyparsons

**Comment by dannyparsons** [comment]
Yes we could. But why not have it just open dlgNewWorksheet for now since that's easy? And then we discuss with @volloholic or @rdstern to see if it's needed/should function differently.

**Comment by dannyparsons** [comment]
Resolved - * button has been removed. Could easily be added back in if needed.
