### ISSUE TITLE
RadioButton Cell Type as a column in the grid does not change the True/False value of the cell when you check/uncheck

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/Instat#885]
See ucrFactor
When bIsMultipleSelector = False the final column of the grid contains radio buttons. But when you check/unchecked these in the grid interactively it doesn't change the True/False value of the cells behind the radio buttons.

This can be tested by putting ucrFactor on a dialog, calling SetReceiver, then SetAsSingleSelector().
Then when running GetSelectedLevels(), nothing is returned even if Radio Buttons are checked. 

If instead SetAsMultipleSelector() is run, Checkboxes are in the final column and GetSelectedLevels() works correctly.

Also, the event CellDataChanged is not triggered by checking a radio button, but it is triggered by checking Checkboxes (because check boxes are changing the True/False values of the cells).

I can't isolate the problem other than that it could be a bug with the gird.

**Comment by dannyparsons** [comment]
@deaspo You might have more luck with this than me, if you get time. I can explain in detail if needed.

**Comment by deaspo** [comment]
Here is the reply from the creators: https://reogrid.net/document/built-in-cell-types/#comment-540
It is a bug that they are trying to fix by the next release.

**Comment by dannyparsons** [comment]
That's great, thanks for contacting them. I wish I had done that before I
spent so long trying to get it working!

For now we will have to use the Checkboxes for both cases then.

**Comment by dannyparsons** [comment]
Resolved by updating to newer version of reogrid.
