### ISSUE TITLE
The bar chart dialogue with summary data

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#890]
1. Make menu item "Bar Chart - Summary Data (also not sub-menu)
2. In Graphics menu delete "Frequency Chart" and "Summary Chart"
3. In Graphics menu, delete Probability Plots and (instead) insert "Cumulative Distribution" below "Wind Rose"
4. For the "Bar Chart - Summary Data" 
- Make dialogue title "Bar Chart from Summary Data"
- Left align "Factor" with "Y Variable"
- For "Second Factor" have "2nd Factor (Optional)".  Always have (Optional) when it is!
- If Pie chart option selected, then hide 2nd factor label and receiver.  It isn't possible to have 2 factors if pie chart selected. 
- Have "Pie Chart Options" and "Bar Chart Options" buttons.  Hide one or other, depending on what option is selected.
5. Sort out VB code using the "Manage > Manipulate > Sort" code from @dannyparsons as a guide.  This to ensure that OK is correctly enabled, Reset works, Help works - code is 328 for this dialogue.  Note that optional controls don't affect the activation of OK.

**Comment by maxwellfundi** [comment]
@dannyparsons This was also fixed.
