### ISSUE TITLE
Options button on Selector

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/Instat#895]
@dannyparsons  What should we do about the options button on the data selector?
we think the name should change to Data Options or something like that and we should at least implement a dummy sub dialog.

**Comment by dannyparsons** [comment]
Yes I agree. Is there someone who could do the dummy dialog quickly and get
it opening from the control?

**Comment by dannyparsons** [comment]
Options button now renamed to Data Options and correctly opens the subdialog.
