### ISSUE TITLE
Inserting a new column with default data or blank?

### ISSUE THREAD

**Issue by deaspo** [africanmathsinitiative/Instat#938]
When inserting a new column, should we have the option to insert it with data or just leave it blank? @rdstern #847

**Comment by rdstern** [comment]
I am happy for it to be left blank.  I envisage though that the visible symbol in the sheets might be other than NA – at least as an option.  Then you can fill it later.

I imagine sometimes we will want to create a blank column and then paste a copy from somewhere else.

Roger

**Comment by deaspo** [comment]
Ok
