### ISSUE TITLE
selecting dataframe$Variable

### ISSUE THREAD

**Issue by Lunalo** [africanmathsinitiative/Instat#977]
Hi Danny,
@africanmathsinitiative/instat 
Thanks for giving this code for getting variables.

`ucrBase.clsRsyntax.AddParameter("x", clsRFunctionParameter:= ucrReceiverRecode.GetVariables()`
unfortunately,this method is not solving my case.The receiver is not accepting variables from the selecting and that is why i used
` ucrBase.clsRsyntax.AddParameter("x", ucrSelectorForRecode.ucrAvailableDataFrames.cboAvailableDataFrames.SelectedItem.ToString & "$" & ucrReceiverRecode.GetVariableNames(False))
which is working. What is your take on this please?

`

**Comment by dannyparsons** [comment]
Ok thanks for bringing up the issue. Can you do a new pull request with your latest code so I can try and see where the problem is?

**Comment by Lunalo** [comment]
Okay Thanks.

**Comment by dannyparsons** [comment]
Can this be closed now?

**Comment by Lunalo** [comment]
Yes.
